/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import PharmacyManagementSystem.PharmacyManagement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author shshe
 */
public class Login extends javax.swing.JFrame {

     int attempt = 0;
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlblusername = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtUsername = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jbtnExit = new javax.swing.JButton();
        jbtnLogin = new javax.swing.JButton();
        jbtnCancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jbtnPharmacyOffice = new javax.swing.JButton();
        jbtnDoctor = new javax.swing.JButton();
        jbtnPharmacy = new javax.swing.JButton();
        jbtnPatient = new javax.swing.JButton();
        jbtnPayment = new javax.swing.JButton();
        jbtnGPAppointment = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbtnHelp = new javax.swing.JButton();
        jbtnSurgery = new javax.swing.JButton();
        jbtnHospital = new javax.swing.JButton();
        jbtnSpecialist = new javax.swing.JButton();
        jbtnConsultant = new javax.swing.JButton();
        jbtnPharmacist = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblusername.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlblusername.setText("Username");
        jPanel1.add(jlblusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        jtxtUsername.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtxtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtUsernameActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 270, -1));

        jPassword.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 270, -1));

        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 170, 60));

        jbtnLogin.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnLogin.setText("Login");
        jbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 170, 60));

        jbtnCancel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnCancel.setText("Cancel");
        jbtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 170, 60));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setText("Login Systems");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 360, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 630, 410));

        jbtnPharmacyOffice.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnPharmacyOffice.setText("Pharmacy Office");
        getContentPane().add(jbtnPharmacyOffice, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 580, 240, 60));

        jbtnDoctor.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnDoctor.setText("Doctor");
        getContentPane().add(jbtnDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 240, 60));

        jbtnPharmacy.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnPharmacy.setText("Pharmacy");
        jbtnPharmacy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPharmacyActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnPharmacy, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 240, 60));

        jbtnPatient.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnPatient.setText("Patient");
        getContentPane().add(jbtnPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 240, 60));

        jbtnPayment.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnPayment.setText("Payment");
        getContentPane().add(jbtnPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 240, 60));

        jbtnGPAppointment.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnGPAppointment.setText("GPAppointment");
        jbtnGPAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGPAppointmentActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnGPAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, 240, 60));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Pharmacy Management System");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel1)
                .addContainerGap(207, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 1120, 130));

        jbtnHelp.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnHelp.setText("Help");
        getContentPane().add(jbtnHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 580, 230, 60));

        jbtnSurgery.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnSurgery.setText("Surgery");
        getContentPane().add(jbtnSurgery, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 230, 230, 60));

        jbtnHospital.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnHospital.setText("Hospital");
        getContentPane().add(jbtnHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 300, 230, 60));

        jbtnSpecialist.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnSpecialist.setText("Specialist");
        getContentPane().add(jbtnSpecialist, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 370, 230, 60));

        jbtnConsultant.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnConsultant.setText("Consultant");
        getContentPane().add(jbtnConsultant, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 440, 230, 60));

        jbtnPharmacist.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnPharmacist.setText("Pharmacist");
        getContentPane().add(jbtnPharmacist, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 510, 230, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtUsernameActionPerformed
private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
   frame = new JFrame("Exit");
   if(JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit","Pharmacy Management Systems",JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION)
   {System.exit(0);}
    }//GEN-LAST:event_jbtnExitActionPerformed
   
    private void jbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoginActionPerformed
      String username = jtxtUsername.getText();
      String password = jPassword.getText();
        if (username.contains("one")&&(password.contains("one"))) {
        jtxtUsername.setText("");
        jPassword.setText("");
        jbtnDoctor.setEnabled(true);
       jbtnPharmacy.setEnabled(true);
       jbtnPatient.setEnabled(true);
       jbtnPayment.setEnabled(true);
       jbtnGPAppointment.setEnabled(true);
       jbtnPharmacyOffice.setEnabled(true);
       jbtnSurgery.setEnabled(true);
       jbtnHospital.setEnabled(true);
       jbtnSpecialist.setEnabled(true);
       jbtnConsultant.setEnabled(true);
       jbtnPharmacist.setEnabled(true);
       jbtnHelp.setEnabled(true);
        }
        else if (!(username.contains("one")&&(password.contains("one")))) {
            jtxtUsername.setText("");
            jPassword.setText("");
            jbtnDoctor.setEnabled(false);
       jbtnPharmacy.setEnabled(false);
       jbtnPatient.setEnabled(false);
       jbtnPayment.setEnabled(false);
       jbtnGPAppointment.setEnabled(false);
       jbtnPharmacyOffice.setEnabled(false);
       jbtnSurgery.setEnabled(false);
       jbtnHospital.setEnabled(false);
       jbtnSpecialist.setEnabled(false);
       jbtnConsultant.setEnabled(false);
       jbtnPharmacist.setEnabled(false);
       jbtnHelp.setEnabled(false);
        attempt++;
            if (attempt ==3) {
                System.exit(0);
            }
        }
      
    }//GEN-LAST:event_jbtnLoginActionPerformed

    private void jbtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelActionPerformed
        jtxtUsername.setText("");
        jPassword.setText("");
    }//GEN-LAST:event_jbtnCancelActionPerformed

    private void jbtnGPAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGPAppointmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnGPAppointmentActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       
      jtxtUsername.setText("");
            jPassword.setText("");
            jbtnDoctor.setEnabled(false);
       jbtnPharmacy.setEnabled(false);
       jbtnPatient.setEnabled(false);
       jbtnPayment.setEnabled(false);
       jbtnGPAppointment.setEnabled(false);
       jbtnPharmacyOffice.setEnabled(false);
       jbtnSurgery.setEnabled(false);
       jbtnHospital.setEnabled(false);
       jbtnSpecialist.setEnabled(false);
       jbtnConsultant.setEnabled(false);
       jbtnPharmacist.setEnabled(false);
       jbtnHelp.setEnabled(false);
       
    }//GEN-LAST:event_formWindowActivated

    private void jbtnPharmacyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPharmacyActionPerformed
       PharmacyManagement myPharmacy = new PharmacyManagement();
       myPharmacy.setVisible(true);
    }//GEN-LAST:event_jbtnPharmacyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JButton jbtnCancel;
    private javax.swing.JButton jbtnConsultant;
    private javax.swing.JButton jbtnDoctor;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnGPAppointment;
    private javax.swing.JButton jbtnHelp;
    private javax.swing.JButton jbtnHospital;
    private javax.swing.JButton jbtnLogin;
    private javax.swing.JButton jbtnPatient;
    private javax.swing.JButton jbtnPayment;
    private javax.swing.JButton jbtnPharmacist;
    private javax.swing.JButton jbtnPharmacy;
    private javax.swing.JButton jbtnPharmacyOffice;
    private javax.swing.JButton jbtnSpecialist;
    private javax.swing.JButton jbtnSurgery;
    private javax.swing.JLabel jlblusername;
    private javax.swing.JTextField jtxtUsername;
    // End of variables declaration//GEN-END:variables
}
