/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacymanagement.View;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import pharmacymanagement.Dao.InsertMedicineDao;
import pharmacymanagement.DaoImp.InsertCompanyDaoImp;
import pharmacymanagement.DaoImp.InsertMedicineDaoImp;
import pharmacymanagement.DaoImp.ProductCategoryDaoImp;
import pharmacymanagement.Pojo.InsertCompany;
import pharmacymanagement.Pojo.InsertMedicine;
import pharmacymanagement.Pojo.ProductCategory;

/**
 *
 * @author shshe
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form AfterLoginPage
     */
    public Dashboard() {
        initComponents();
        displayDataintoTable();
    }

    public void clearTable() {
        DefaultTableModel model = (DefaultTableModel) jTableDashBoardDipsplay.getModel();
        model.setRowCount(0);
    }

    public void displayDataintoTable() {
        clearTable();
        InsertMedicineDao ic = new InsertMedicineDaoImp();
        DefaultTableModel model = (DefaultTableModel) jTableDashBoardDipsplay.getModel();
        List<InsertMedicine> list = ic.getInsertMedicine();
        Object[] cols = new Object[11];
        for (int i = 0; i < list.size(); i++) {
            cols[0] = list.get(i).getProductId();
            cols[1] = list.get(i).getProductName();
            cols[2] = list.get(i).getProductCode();
            cols[3] = list.get(i).getMedicineGroup();
             InsertCompany ik = new InsertCompanyDaoImp().getInsertCompanyById(list.get(i).getProductId());
            cols[4] = ik.getCompanyName();
            ProductCategory pc = new ProductCategoryDaoImp().getProductCategorybyId(list.get(i).getProductId());
            cols[5] = pc.getProductCategoryName();

            cols[6] = list.get(i).getProductQuantity();
            cols[7] = list.get(i).getProductPrice();
            cols[8] = list.get(i).getExpireDate();
            cols[9] = list.get(i).getDoseType();
            cols[10] = list.get(i).getRemarks();
            model.addRow(cols);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAfterLoginIcon = new javax.swing.JLabel();
        jButtonMedicines = new javax.swing.JButton();
        jButtonCompanies = new javax.swing.JButton();
        jButtonViewSaleRecords = new javax.swing.JButton();
        jButtonNewSales = new javax.swing.JButton();
        jButtonChangePassword = new javax.swing.JButton();
        jButtonCreateAUser = new javax.swing.JButton();
        jButtonSearch = new javax.swing.JButton();
        jTextFieldSearch = new javax.swing.JTextField();
        jButtonLogout1 = new javax.swing.JButton();
        jLabelDisplayLoggedInUser = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDashBoardDipsplay = new javax.swing.JTable();
        jButtonProductCategory = new javax.swing.JButton();
        jButtonChangeSummary = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelAfterLoginIcon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAfterLoginIcon.setText("Login Icon");

        jButtonMedicines.setText("Medicines");
        jButtonMedicines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedicinesActionPerformed(evt);
            }
        });

        jButtonCompanies.setText("Companies");
        jButtonCompanies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCompaniesActionPerformed(evt);
            }
        });

        jButtonViewSaleRecords.setText("View Sale Records");
        jButtonViewSaleRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewSaleRecordsActionPerformed(evt);
            }
        });

        jButtonNewSales.setText("New Sales");
        jButtonNewSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewSalesActionPerformed(evt);
            }
        });

        jButtonChangePassword.setText("Change Password");
        jButtonChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangePasswordActionPerformed(evt);
            }
        });

        jButtonCreateAUser.setText("Create a User");

        jButtonSearch.setText("Search");

        jTextFieldSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldSearch.setText("If i search by 'a' it wil show all medicines  start with a");

        jButtonLogout1.setText("Log Out");
        jButtonLogout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogout1ActionPerformed(evt);
            }
        });

        jLabelDisplayLoggedInUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelDisplayLoggedInUser.setText("You are looged in as: shetu");

        jTableDashBoardDipsplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Product Code", "Medicine Group", "Company Name", "Product Category", "Quantity", "Price Per Unit", "Expire Date", "DoseType", "Remarks"
            }
        ));
        jScrollPane1.setViewportView(jTableDashBoardDipsplay);

        jButtonProductCategory.setText("Product Category");
        jButtonProductCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProductCategoryActionPerformed(evt);
            }
        });

        jButtonChangeSummary.setText("Summary ");
        jButtonChangeSummary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangeSummaryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAfterLoginIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLogout1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCompanies, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMedicines, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonViewSaleRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNewSales, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCreateAUser, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonProductCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonChangeSummary, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelDisplayLoggedInUser, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(34, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSearch))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelDisplayLoggedInUser))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelAfterLoginIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonProductCategory)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMedicines)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCompanies)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonViewSaleRecords)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonNewSales)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonChangePassword)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonChangeSummary)
                        .addGap(105, 105, 105)
                        .addComponent(jButtonCreateAUser)
                        .addGap(7, 7, 7)
                        .addComponent(jButtonLogout1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMedicinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedicinesActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new MedicinesPage().setVisible(true);
    }//GEN-LAST:event_jButtonMedicinesActionPerformed

    private void jButtonCompaniesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCompaniesActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new CompanyPage().setVisible(true);
    }//GEN-LAST:event_jButtonCompaniesActionPerformed

    private void jButtonViewSaleRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewSaleRecordsActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ViewSaleRecord().setVisible(true);
    }//GEN-LAST:event_jButtonViewSaleRecordsActionPerformed

    private void jButtonNewSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewSalesActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new NewSales().setVisible(true);
    }//GEN-LAST:event_jButtonNewSalesActionPerformed

    private void jButtonChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangePasswordActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ChangePassword().setVisible(true);
    }//GEN-LAST:event_jButtonChangePasswordActionPerformed

    private void jButtonProductCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProductCategoryActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ProductCategoryView().setVisible(true);
    }//GEN-LAST:event_jButtonProductCategoryActionPerformed

    private void jButtonLogout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogout1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new LoginPage().setVisible(true);
    }//GEN-LAST:event_jButtonLogout1ActionPerformed

    private void jButtonChangeSummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangeSummaryActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new SummaryView().setVisible(true);
    }//GEN-LAST:event_jButtonChangeSummaryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonChangePassword;
    private javax.swing.JButton jButtonChangeSummary;
    private javax.swing.JButton jButtonCompanies;
    private javax.swing.JButton jButtonCreateAUser;
    private javax.swing.JButton jButtonLogout1;
    private javax.swing.JButton jButtonMedicines;
    private javax.swing.JButton jButtonNewSales;
    private javax.swing.JButton jButtonProductCategory;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonViewSaleRecords;
    private javax.swing.JLabel jLabelAfterLoginIcon;
    private javax.swing.JLabel jLabelDisplayLoggedInUser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDashBoardDipsplay;
    private javax.swing.JTextField jTextFieldSearch;
    // End of variables declaration//GEN-END:variables
}
