/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import daoImp.BuyDrugDaoImp;
import daoImp.CompanyDaoImp;
import daoImp.DrugDaoImp;
import daoImp.SummaryDaoImp;
import daoImp.UserDaoImp;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.time.LocalDate;
import java.time.Period;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import pojo.BuyDrug;
import pojo.Company;
import pojo.Drug;
import pojo.Summary;
import pojo.User;

/**
 *
 * @author shshe
 */
public class AddDrugView extends javax.swing.JFrame {

    /**
     * Creates new form AddDrugView
     */
    public AddDrugView() {
        initComponents();
        //drug button
        jButtonUpdateDrug.setEnabled(false);
        jButtonDeleteDrug.setEnabled(false);
        /////
        jTextFieldExpireTime.setEditable(true);
        //////
        new DrugDaoImp().createTable();
        displayDataIntoDrugTypeComboBox();
        displayDataIntoCompanyNameComboBox();
    }

    public void displayDataIntoCompanyNameComboBox() {
        List<Company> list = new CompanyDaoImp().getCompany();
        jComboBoxCompanyName.addItem("Select A Company");
        for (Company c : list) {
            jComboBoxCompanyName.addItem(c.getCompany_name());
        }
    }

    //display data into drug type combo
    public void displayDataIntoDrugTypeComboBox() {
        List<BuyDrug> list = new BuyDrugDaoImp().getBuyDrug();
        jComboBoxDrugType.addItem("Select A Drug Type");
        for (BuyDrug c : list) {
            jComboBoxDrugType.addItem(c.getDrug_type());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldDrugName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDrugBarCode = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldDrugDose = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldDrugGroup = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldDrugBuyingPrice = new javax.swing.JTextField();
        jTextFieldDrugSellingPrice = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldDrugTax = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButtonUpdateDrug = new javax.swing.JButton();
        jButtonDeleteDrug = new javax.swing.JButton();
        jButtonDrugsList = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jButtonAddDrug = new javax.swing.JButton();
        jComboBoxCompanyName = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jTextFieldExpireTime = new javax.swing.JTextField();
        jComboBoxDrugQuantity = new javax.swing.JComboBox<>();
        jComboBoxSection = new javax.swing.JComboBox<>();
        jComboBoxPlace = new javax.swing.JComboBox<>();
        jComboBoxPDay = new javax.swing.JComboBox<>();
        jComboBoxPMonth = new javax.swing.JComboBox<>();
        jComboBoxPYear = new javax.swing.JComboBox<>();
        jComboBoxEYear = new javax.swing.JComboBox<>();
        jComboBoxEMonth = new javax.swing.JComboBox<>();
        jComboBoxEDay = new javax.swing.JComboBox<>();
        jComboBoxDrugType = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Drug Form");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Drug Name:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        jTextFieldDrugName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldDrugName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldDrugNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldDrugNameKeyReleased(evt);
            }
        });
        jPanel2.add(jTextFieldDrugName, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 11, 196, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Drug Type:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 84, -1, -1));

        jTextFieldDrugBarCode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldDrugBarCode.setText("lapa");
        jPanel2.add(jTextFieldDrugBarCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 156, 200, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Drug Barcode:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 159, -1, -1));

        jTextFieldDrugDose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldDrugDose.setText("japa");
        jPanel2.add(jTextFieldDrugDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 211, 200, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Drug Dose:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 214, -1, -1));

        jTextFieldDrugGroup.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(jTextFieldDrugGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 261, 190, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Drug Group:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 264, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Drug Buying Price:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 305, -1, -1));

        jTextFieldDrugBuyingPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldDrugBuyingPrice.setText("10");
        jPanel2.add(jTextFieldDrugBuyingPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 302, 192, -1));

        jTextFieldDrugSellingPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldDrugSellingPrice.setText("20");
        jPanel2.add(jTextFieldDrugSellingPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 343, 192, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Drug Selling Price:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 346, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Company Name:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 22, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Production Date:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 70, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Expire Date:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 122, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Drug Tax:");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 237, -1, -1));

        jTextFieldDrugTax.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldDrugTax.setText("3%");
        jTextFieldDrugTax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldDrugTaxKeyPressed(evt);
            }
        });
        jPanel2.add(jTextFieldDrugTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 234, 196, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Drug Place:");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 305, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Drug Quantity:");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 346, -1, -1));

        jButtonUpdateDrug.setBackground(new java.awt.Color(0, 102, 102));
        jButtonUpdateDrug.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonUpdateDrug.setText("Update Drug");
        jPanel2.add(jButtonUpdateDrug, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 388, -1, -1));

        jButtonDeleteDrug.setBackground(new java.awt.Color(0, 102, 102));
        jButtonDeleteDrug.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDeleteDrug.setText("Delete Drug");
        jPanel2.add(jButtonDeleteDrug, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 388, -1, -1));

        jButtonDrugsList.setBackground(new java.awt.Color(0, 102, 102));
        jButtonDrugsList.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDrugsList.setText("Drugs List");
        jPanel2.add(jButtonDrugsList, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 388, -1, -1));

        jButtonClear.setBackground(new java.awt.Color(0, 102, 102));
        jButtonClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonClear.setText("Clear");
        jPanel2.add(jButtonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 388, -1, -1));

        jButtonCancel.setBackground(new java.awt.Color(0, 102, 102));
        jButtonCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 390, -1, -1));

        jButtonAddDrug.setBackground(new java.awt.Color(0, 102, 102));
        jButtonAddDrug.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAddDrug.setText("Add Drug");
        jButtonAddDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddDrugActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAddDrug, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 388, -1, -1));

        jComboBoxCompanyName.setBackground(new java.awt.Color(0, 102, 102));
        jComboBoxCompanyName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(jComboBoxCompanyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 11, 199, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Expire Time:");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 173, -1, -1));

        jTextFieldExpireTime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldExpireTime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldExpireTimeMouseClicked(evt);
            }
        });
        jTextFieldExpireTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldExpireTimeActionPerformed(evt);
            }
        });
        jTextFieldExpireTime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldExpireTimeKeyPressed(evt);
            }
        });
        jPanel2.add(jTextFieldExpireTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 170, 196, -1));

        jComboBoxDrugQuantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxDrugQuantity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pieces or Box", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "45", "46", "47", "48", "49", "50" }));
        jPanel2.add(jComboBoxDrugQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 343, 168, -1));

        jComboBoxSection.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxSection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Section:", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z" }));
        jPanel2.add(jComboBoxSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 296, -1, -1));

        jComboBoxPlace.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxPlace.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Place:", "Left", "Right", "Up", "Down" }));
        jPanel2.add(jComboBoxPlace, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 296, -1, -1));

        jComboBoxPDay.setBackground(new java.awt.Color(0, 102, 102));
        jComboBoxPDay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxPDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day:", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboBoxPDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPDayActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBoxPDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 67, -1, -1));

        jComboBoxPMonth.setBackground(new java.awt.Color(0, 102, 102));
        jComboBoxPMonth.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxPMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month:", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jPanel2.add(jComboBoxPMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 80, -1));

        jComboBoxPYear.setBackground(new java.awt.Color(0, 102, 102));
        jComboBoxPYear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxPYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year:", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        jPanel2.add(jComboBoxPYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, 72, -1));

        jComboBoxEYear.setBackground(new java.awt.Color(0, 102, 102));
        jComboBoxEYear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxEYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year:", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        jPanel2.add(jComboBoxEYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(686, 122, 72, -1));

        jComboBoxEMonth.setBackground(new java.awt.Color(0, 102, 102));
        jComboBoxEMonth.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxEMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month:", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jPanel2.add(jComboBoxEMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, -1, -1));

        jComboBoxEDay.setBackground(new java.awt.Color(0, 102, 102));
        jComboBoxEDay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxEDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day:", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel2.add(jComboBoxEDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, -1, -1));

        jComboBoxDrugType.setBackground(new java.awt.Color(0, 102, 102));
        jComboBoxDrugType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(jComboBoxDrugType, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 81, 199, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
     User user = new UserDaoImp().getUserByUserName(LoginView.user_name);
        if (user.getRoleName().equalsIgnoreCase("admin")) {
            this.setVisible(false);
            new AdministrationDashBoard().setVisible(true);
        } else if (user.getRoleName().equalsIgnoreCase("employee")) {
            this.setVisible(false);
            new EmployeeDashBoard().setVisible(true);
        }
    }//GEN-LAST:event_jButtonCancelActionPerformed
    ///for expire time
    int tot_qty = 0;
    int av_qty = 0;
    int sl_qty = 0;
    private void jButtonAddDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddDrugActionPerformed
        // TODO add your handling code here:
        //validation
        try {
            if (jTextFieldDrugName.getText().trim().length() < 3) {
                JOptionPane.showMessageDialog(null, "Drug Name should be atleast 3 characters!");
            } else if (jComboBoxDrugType.getItemAt(jComboBoxDrugType.getSelectedIndex()).equals("Select A Drug Type")) {
                JOptionPane.showMessageDialog(null, "Please select the drug type!");
            } else if (jTextFieldDrugBarCode.getText().trim().length() < 3) {
                JOptionPane.showMessageDialog(null, "Drug BarCode should be atleast 3 characters!");
            } else if (jTextFieldDrugGroup.getText().trim().length() < 3) {
                JOptionPane.showMessageDialog(null, "Drug Code should be atleast 3 characters!");
            } else if (jTextFieldDrugBuyingPrice.getText().trim().length() < 1) {
                JOptionPane.showMessageDialog(null, "Enter the buying price!");
            } else if (jTextFieldDrugSellingPrice.getText().trim().length() < 1) {
                JOptionPane.showMessageDialog(null, "Enter the selling price!");
            } else if (jComboBoxCompanyName.getItemAt(jComboBoxCompanyName.getSelectedIndex()).equals("Select A Company")) {
                JOptionPane.showMessageDialog(null, "Select A Company!");
            } else if (jComboBoxPDay.getItemAt(jComboBoxPDay.getSelectedIndex()).equals("Day:") || jComboBoxPMonth.getItemAt(jComboBoxPMonth.getSelectedIndex()).equals("Month:") || jComboBoxPYear.getItemAt(jComboBoxPYear.getSelectedIndex()).equals("Year:")) {
                JOptionPane.showMessageDialog(null, "Please select the Production date correctly!");
            } else if (jComboBoxEDay.getItemAt(jComboBoxEDay.getSelectedIndex()).equals("Day:") || jComboBoxEMonth.getItemAt(jComboBoxEMonth.getSelectedIndex()).equals("Month:") || jComboBoxEYear.getItemAt(jComboBoxEYear.getSelectedIndex()).equals("Year:")) {
                JOptionPane.showMessageDialog(null, "Please select the Expire date correctly!");
            } else if ((jComboBoxPDay.getItemAt(jComboBoxPDay.getSelectedIndex())).equals("Day:") || (jComboBoxPMonth.getItemAt(jComboBoxPMonth.getSelectedIndex())).equals("Month:") || (jComboBoxPYear.getItemAt(jComboBoxPYear.getSelectedIndex())).equals("Year:") || (jComboBoxEDay.getItemAt(jComboBoxEDay.getSelectedIndex())).equals("Day:") || (jComboBoxEMonth.getItemAt(jComboBoxEMonth.getSelectedIndex())).equals("Month:") || (jComboBoxEYear.getItemAt(jComboBoxEYear.getSelectedIndex())).equals("Year:")) {
                JOptionPane.showMessageDialog(null, "Please select the Production Date And Expire Date correctly!");
            } else if (jTextFieldDrugTax.getText().trim().length() < 1) {
                JOptionPane.showMessageDialog(null, "Please enter the drug tax!");

            } else if (jComboBoxSection.getItemAt(jComboBoxSection.getSelectedIndex()).equals("Section:") || jComboBoxPlace.getItemAt(jComboBoxPlace.getSelectedIndex()).equals("Place:")) {
                JOptionPane.showMessageDialog(null, "Please select the drug place!");
            } else if (jComboBoxDrugQuantity.getItemAt(jComboBoxDrugQuantity.getSelectedIndex()).equals("Pieces or Box")) {
                JOptionPane.showMessageDialog(null, "Please select the quantity!");
            } else {
                String drug_name = jTextFieldDrugName.getText().trim();
                String drug_type = jComboBoxDrugType.getItemAt(jComboBoxDrugType.getSelectedIndex());
                String drug_barcode = jTextFieldDrugBarCode.getText().trim();
                String drug_dose = jTextFieldDrugDose.getText().trim();
                String drug_code = jTextFieldDrugGroup.getText().trim();
                double drug_buy_price = Double.parseDouble(jTextFieldDrugBuyingPrice.getText().trim());
                double drug_sell_price = Double.parseDouble(jTextFieldDrugSellingPrice.getText().trim());
                //company
                String company = jComboBoxCompanyName.getItemAt(jComboBoxCompanyName.getSelectedIndex());
                ////////////////
                int d = Integer.parseInt(jComboBoxPDay.getItemAt(jComboBoxPDay.getSelectedIndex()));
                int m = Integer.parseInt(jComboBoxPMonth.getItemAt(jComboBoxPMonth.getSelectedIndex()));
                int y = Integer.parseInt(jComboBoxPYear.getItemAt(jComboBoxPYear.getSelectedIndex()));
                Date production_date = Date.valueOf(y + "-" + m + "-" + d);
                ////////////////////////////////////
                int d1 = Integer.parseInt(jComboBoxEDay.getItemAt(jComboBoxEDay.getSelectedIndex()));
                int m1 = Integer.parseInt(jComboBoxEMonth.getItemAt(jComboBoxEMonth.getSelectedIndex()));
                int y1 = Integer.parseInt(jComboBoxEYear.getItemAt(jComboBoxEYear.getSelectedIndex()));
                Date expire_date = Date.valueOf(y1 + "-" + m1 + "-" + d1);
                LocalDate pdate = LocalDate.of(y, m, d);
                LocalDate edate = LocalDate.of(y1, m1, d1);
                Period diff = Period.between(pdate, edate);
                String expire_time = diff.getYears() + " year " + diff.getMonths() + " month " + diff.getDays() + " day ";
                String drug_tax = jTextFieldDrugTax.getText().trim();
                Pattern pattern1 = Pattern.compile("\\d+\\.\\d+"); //compile will work for pattern
                Pattern pattern2 = Pattern.compile("\\d+"); //compile will work for pattern
                Matcher matcher1 = pattern1.matcher(drug_tax);
                Matcher matcher2 = pattern2.matcher(drug_tax);
                double dtax = 0;
                if (matcher1.find()) {
                    dtax = Double.parseDouble(matcher1.group(0));
                } else if (matcher2.find()) {
                    dtax = Double.parseDouble(matcher2.group(0));
                }
                String s = jComboBoxSection.getItemAt(jComboBoxSection.getSelectedIndex());
                String p = jComboBoxPlace.getItemAt(jComboBoxPlace.getSelectedIndex());
                String drug_place = s + "-" + p;
                int drug_qty = Integer.parseInt(jComboBoxDrugQuantity.getItemAt(jComboBoxDrugQuantity.getSelectedIndex()));
                try {
                    Company com = new CompanyDaoImp().getCompanyByName(company);
                    //String drug_name, String drug_type, String drug_barcode, String drug_dose, String drug_code, double drug_buy_price, double drug_sell_price, Company company, Date production_date, Date expire_date, String expire_time, double drug_tax, String drug_place, int drug_quantity)
                    Drug drug = new Drug(drug_name, drug_type, drug_barcode, drug_dose, drug_code, drug_buy_price, drug_sell_price, com, production_date, expire_date, expire_time, dtax, drug_place, drug_qty);
                    Drug existDrug = new DrugDaoImp().getDrugByDrugName(drug_name);
                    //summary input = if drug is not inputted first then input first else update it

                    //collect data from combo box
                    int dt = Integer.parseInt(jComboBoxEDay.getItemAt(jComboBoxEDay.getSelectedIndex()));
                    int mo = Integer.parseInt(jComboBoxEMonth.getItemAt(jComboBoxEMonth.getSelectedIndex()));
                    int ye = Integer.parseInt(jComboBoxEYear.getItemAt(jComboBoxEYear.getSelectedIndex()));

                    //////////////////////////////////// 
                    Date date = new Date(System.currentTimeMillis());
                    String[] dx = String.valueOf(date).split("-");
                    int ye2 = Integer.parseInt(dx[0]);
                    int mo2 = Integer.parseInt(dx[1]);
                    int dt2 = Integer.parseInt(dx[2]);
                    //today date
                    LocalDate today_date = LocalDate.of(ye2, mo2, dt2);
                    LocalDate ex_date = LocalDate.of(ye, mo, dt);
                    Period diff1 = Period.between(today_date, ex_date);
                    String validity = diff1.getYears() + " year " + diff1.getMonths() + " month " + diff1.getDays() + " day ";

                    //combox data collection ends
                    Summary sum = new Summary(drug_name, drug_type, drug_barcode, drug_dose, drug_code, drug_buy_price, drug_sell_price, com, production_date, expire_date, expire_time, validity, dtax, drug_place, drug_qty, drug_qty, 0);
                    if (existDrug.getDrug_name() != null) {
                        JOptionPane.showMessageDialog(null, "Drug Already exists!");
                        //summary update
                        tot_qty += drug_qty;
                        av_qty += drug_qty;
                        Summary sum1 = new Summary(drug_name, drug_type, drug_barcode, drug_dose, drug_code, drug_buy_price, drug_sell_price, com, production_date, expire_date, expire_time, validity, dtax, drug_place, tot_qty, av_qty, 0);
                        new SummaryDaoImp().updateSum(sum1);
                        JOptionPane.showMessageDialog(null, "Data is added successfully in summary table!");

                    } else {
                        new DrugDaoImp().insert(drug);
                        JOptionPane.showMessageDialog(null, "Data successfully inserted into database table:drug!");
                        new SummaryDaoImp().insert(sum);
                        JOptionPane.showMessageDialog(null, "Data successfully inserted into database table:summary!");

                    }
                } catch (Exception e) {
                    Company com = new CompanyDaoImp().getCompanyByName(company);
                    //String drug_name, String drug_type, String drug_barcode, String drug_dose, String drug_code, double drug_buy_price, double drug_sell_price, Company company, Date production_date, Date expire_date, String expire_time, double drug_tax, String drug_place, int drug_quantity)
                    Drug drug = new Drug(drug_name, drug_type, drug_barcode, drug_dose, drug_code, drug_buy_price, drug_sell_price, com, production_date, expire_date, expire_time, dtax, drug_place, drug_qty);

                    new DrugDaoImp().insert(drug);
                    JOptionPane.showMessageDialog(null, "Data successfully inserted into database table:drug!");
                    //collect data from combo box
                    int dt = Integer.parseInt(jComboBoxEDay.getItemAt(jComboBoxEDay.getSelectedIndex()));
                    int mo = Integer.parseInt(jComboBoxEMonth.getItemAt(jComboBoxEMonth.getSelectedIndex()));
                    int ye = Integer.parseInt(jComboBoxEYear.getItemAt(jComboBoxEYear.getSelectedIndex()));

                    //////////////////////////////////// 
                    Date date = new Date(System.currentTimeMillis());
                    String[] dx = String.valueOf(date).split("-");
                    int ye2 = Integer.parseInt(dx[0]);
                    int mo2 = Integer.parseInt(dx[1]);
                    int dt2 = Integer.parseInt(dx[2]);
                    //today date
                    LocalDate today_date = LocalDate.of(ye2, mo2, dt2);
                    LocalDate ex_date = LocalDate.of(ye, mo, dt);
                    Period diff1 = Period.between(today_date, ex_date);
                    String validity = diff1.getYears() + " year " + diff1.getMonths() + " month " + diff1.getDays() + " day ";

                    //combox data collection ends
//                    Date date = new Date(System.currentTimeMillis());
//                    String[] dx = String.valueOf(date).split("-");
//                    int y2 = Integer.parseInt(dx[0]);
//                    int m2 = Integer.parseInt(dx[1]);
//                    int d2 = Integer.parseInt(dx[2]);
//                    LocalDate today_date = LocalDate.of(y2, m2, d2);
//                    Period diff1 = Period.between(today_date, edate);
//                    String validity = diff1.getYears() + " year " + diff1.getMonths() + " month " + diff1.getDays() + " day ";
                    Summary sum = new Summary(drug_name, drug_type, drug_barcode, drug_dose, drug_code, drug_buy_price, drug_sell_price, com, production_date, expire_date, expire_time, validity, dtax, drug_place, drug_qty, drug_qty, 0);
                    new SummaryDaoImp().insert(sum);
                    JOptionPane.showMessageDialog(null, "Data successfully inserted into database table:summary!");
                }
            }

        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Please correct the number fields!");

        }

    }//GEN-LAST:event_jButtonAddDrugActionPerformed

    private void jTextFieldDrugTaxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDrugTaxKeyPressed


    }//GEN-LAST:event_jTextFieldDrugTaxKeyPressed

    private void jTextFieldExpireTimeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldExpireTimeKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextFieldExpireTimeKeyPressed

    private void jTextFieldExpireTimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldExpireTimeMouseClicked
        // TODO add your handling code here:
        if ((jComboBoxPDay.getItemAt(jComboBoxPDay.getSelectedIndex())).equals("Day:") || (jComboBoxPMonth.getItemAt(jComboBoxPMonth.getSelectedIndex())).equals("Month:") || (jComboBoxPYear.getItemAt(jComboBoxPYear.getSelectedIndex())).equals("Year:") || (jComboBoxEDay.getItemAt(jComboBoxEDay.getSelectedIndex())).equals("Day:") || (jComboBoxEMonth.getItemAt(jComboBoxEMonth.getSelectedIndex())).equals("Month:") || (jComboBoxEYear.getItemAt(jComboBoxEYear.getSelectedIndex())).equals("Year:")) {
            JOptionPane.showMessageDialog(null, "Please select the Production Date And Expire Date correctly!");
        } else {
            int d = Integer.parseInt(jComboBoxPDay.getItemAt(jComboBoxPDay.getSelectedIndex()));
            int m = Integer.parseInt(jComboBoxPMonth.getItemAt(jComboBoxPMonth.getSelectedIndex()));
            int y = Integer.parseInt(jComboBoxPYear.getItemAt(jComboBoxPYear.getSelectedIndex()));
            Date production_date = Date.valueOf(y + "-" + m + "-" + d);
            ////////////////////////////////////
            int d1 = Integer.parseInt(jComboBoxEDay.getItemAt(jComboBoxEDay.getSelectedIndex()));
            int m1 = Integer.parseInt(jComboBoxEMonth.getItemAt(jComboBoxEMonth.getSelectedIndex()));
            int y1 = Integer.parseInt(jComboBoxEYear.getItemAt(jComboBoxEYear.getSelectedIndex()));
            Date expire_date = Date.valueOf(y1 + "-" + m1 + "-" + d1);
            LocalDate pdate = LocalDate.of(y, m, d);
            LocalDate edate = LocalDate.of(y1, m1, d1);
            Period diff = Period.between(pdate, edate);
            String expire_time = diff.getYears() + " year " + diff.getMonths() + " month " + diff.getDays() + " day ";
            jTextFieldExpireTime.setText(expire_time);
        }
    }//GEN-LAST:event_jTextFieldExpireTimeMouseClicked

    private void jTextFieldExpireTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldExpireTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldExpireTimeActionPerformed

    private void jTextFieldDrugNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDrugNameKeyReleased
        
    }//GEN-LAST:event_jTextFieldDrugNameKeyReleased

    private void jTextFieldDrugNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDrugNameKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        // TODO add your handling code here:
        String drug_name = jTextFieldDrugName.getText().trim();
        BuyDrug bd = new BuyDrugDaoImp().getBuyDrugByDrugName(drug_name);
        if (bd.getDrug_name() != null) {
            //vairables
            String drug_barcode = String.valueOf(new BuyDrugDaoImp().getBuyDrugByDrugName(drug_name).getBar_code());
            String drug_type = String.valueOf(new BuyDrugDaoImp().getBuyDrugByDrugName(drug_name).getDrug_type());
            String drug_group = String.valueOf(new BuyDrugDaoImp().getBuyDrugByDrugName(drug_name).getDrug_group());
            Company com = new CompanyDaoImp().getCompanyById(new BuyDrugDaoImp().getBuyDrugByDrugName(drug_name).getCompany().getCompany_id());
            String company_name = com.getCompany_name();
            int qty = new BuyDrugDaoImp().getBuyDrugByDrugName(drug_name).getQuantity();
            double buy_price = new BuyDrugDaoImp().getBuyDrugByDrugName(drug_name).getBuy_price();;
            double amount = new BuyDrugDaoImp().getBuyDrugByDrugName(drug_name).getAmount();
            //set
            //combo box drug type
            jComboBoxDrugType.removeAllItems();
            jComboBoxDrugType.addItem(drug_type);
            //barcode
            jTextFieldDrugBarCode.setText(drug_barcode);
            jTextFieldDrugGroup.setText(drug_group);
            //company name
            jComboBoxCompanyName.removeAllItems();
            jComboBoxCompanyName.addItem(company_name);

            //quantity
            jComboBoxDrugQuantity.removeAllItems();
            jComboBoxDrugQuantity.addItem(String.valueOf(qty));
            //buy price
            jTextFieldDrugBuyingPrice.setText(String.valueOf(buy_price));
            //amount
            //there should be an amount
        }else{
        
        }
        }
    }//GEN-LAST:event_jTextFieldDrugNameKeyPressed

    private void jComboBoxPDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPDayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDrugView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDrugView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDrugView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDrugView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDrugView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddDrug;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDeleteDrug;
    private javax.swing.JButton jButtonDrugsList;
    private javax.swing.JButton jButtonUpdateDrug;
    private javax.swing.JComboBox<String> jComboBoxCompanyName;
    private javax.swing.JComboBox<String> jComboBoxDrugQuantity;
    private javax.swing.JComboBox<String> jComboBoxDrugType;
    private javax.swing.JComboBox<String> jComboBoxEDay;
    private javax.swing.JComboBox<String> jComboBoxEMonth;
    private javax.swing.JComboBox<String> jComboBoxEYear;
    private javax.swing.JComboBox<String> jComboBoxPDay;
    private javax.swing.JComboBox<String> jComboBoxPMonth;
    private javax.swing.JComboBox<String> jComboBoxPYear;
    private javax.swing.JComboBox<String> jComboBoxPlace;
    private javax.swing.JComboBox<String> jComboBoxSection;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldDrugBarCode;
    private javax.swing.JTextField jTextFieldDrugBuyingPrice;
    private javax.swing.JTextField jTextFieldDrugDose;
    private javax.swing.JTextField jTextFieldDrugGroup;
    private javax.swing.JTextField jTextFieldDrugName;
    private javax.swing.JTextField jTextFieldDrugSellingPrice;
    private javax.swing.JTextField jTextFieldDrugTax;
    private javax.swing.JTextField jTextFieldExpireTime;
    // End of variables declaration//GEN-END:variables
}
