/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author shshe
 */
public class AdministrationDashBoard extends javax.swing.JFrame {

    /**
     * Creates new form AdministrationDashBoard
     */
    public AdministrationDashBoard() {
        initComponents();
        //user buttons
        jButtonAddUser.setVisible(false);
        jButtonUpdateUser.setVisible(false);
        jButtonDeleteUser.setVisible(false);
        //drug buttons
        jButtonAddDrug.setVisible(false);
        jButtonDeleteDrug.setVisible(false);
        jButtonUpdateDrug.setVisible(false);
        jButtonSearchDrug.setVisible(false);
        jButtonMoveDrug.setVisible(false);
        jButtonDrugsList.setVisible(false);

        //Drug details
        jButtonCheckPlaces.setVisible(false);
        jButtonEditPrices.setVisible(false);
        jButtonExpireDrugs.setVisible(false);
        jButtonRenewValidity.setVisible(false);
        jButtonAlmostFinished.setVisible(false);

        //purchases
        jButtonBuyDrugs.setVisible(false);
        jButtonUpdateDeals.setVisible(false);
        jButtonDealList.setVisible(false);

        //Sales
        jButtonSalesBill.setVisible(false);
        jButtonShiftSales.setVisible(false);

        //Company
        jButtonAddCompany.setVisible(false);
        jButtonUpdateCompany.setVisible(false);
        jButtonDeleteCompany.setVisible(false);

        //Settings
        jButtonLoginDetails.setVisible(false);
        jButtonChangePassword.setVisible(false);
        jButtonLogout.setVisible(false);

        //Record
        jButtonSummary.setVisible(false);
        jButtonDailyRecord.setVisible(false);
        jButtonClientList.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelTime = new javax.swing.JLabel();
        jLabelDay = new javax.swing.JLabel();
        jButtonExit = new javax.swing.JButton();
        jLabelDay1 = new javax.swing.JLabel();
        jButtonInbox = new javax.swing.JButton();
        jButtonSettings = new javax.swing.JButton();
        jButtonSettingCompany = new javax.swing.JButton();
        jButtonSales = new javax.swing.JButton();
        jButtonPurchases = new javax.swing.JButton();
        jButtonDrugDetails = new javax.swing.JButton();
        jButtonDrugs = new javax.swing.JButton();
        jButtonUser = new javax.swing.JButton();
        jButtonAddUser = new javax.swing.JButton();
        jButtonDeleteUser = new javax.swing.JButton();
        jButtonUpdateUser = new javax.swing.JButton();
        jButtonAddDrug = new javax.swing.JButton();
        jButtonDeleteDrug = new javax.swing.JButton();
        jButtonUpdateDrug = new javax.swing.JButton();
        jButtonSearchDrug = new javax.swing.JButton();
        jButtonDrugsList = new javax.swing.JButton();
        jButtonMoveDrug = new javax.swing.JButton();
        jButtonCheckPlaces = new javax.swing.JButton();
        jButtonEditPrices = new javax.swing.JButton();
        jButtonExpireDrugs = new javax.swing.JButton();
        jButtonRenewValidity = new javax.swing.JButton();
        jButtonAlmostFinished = new javax.swing.JButton();
        jButtonBuyDrugs = new javax.swing.JButton();
        jButtonUpdateDeals = new javax.swing.JButton();
        jButtonDealList = new javax.swing.JButton();
        jButtonSalesBill = new javax.swing.JButton();
        jButtonShiftSales = new javax.swing.JButton();
        jButtonLoginDetails = new javax.swing.JButton();
        jButtonChangePassword = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jButtonAddCompany = new javax.swing.JButton();
        jButtonUpdateCompany = new javax.swing.JButton();
        jButtonDeleteCompany = new javax.swing.JButton();
        jButtonRecord = new javax.swing.JButton();
        jButtonSummary = new javax.swing.JButton();
        jButtonDailyRecord = new javax.swing.JButton();
        jButtonClientList = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Pharmacy Management");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("(Administration)");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Time");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Monday");

        jLabelTime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTime.setText("10:58:44");

        jLabelDay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelDay.setText("10-02-2019");

        jButtonExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jLabelDay1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelDay1.setText("Logged in: Shetu");

        jButtonInbox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonInbox.setText("Inbox");
        jButtonInbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonExit)
                        .addGap(60, 60, 60)
                        .addComponent(jButtonInbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabelDay1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(118, 118, 118)
                        .addComponent(jLabelTime)
                        .addGap(116, 116, 116)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelDay)
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonExit)
                        .addComponent(jButtonInbox)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelDay, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTime, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelDay1)
                .addContainerGap())
        );

        jButtonSettings.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSettings.setText("Settings");
        jButtonSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSettingsActionPerformed(evt);
            }
        });

        jButtonSettingCompany.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSettingCompany.setText("Company");
        jButtonSettingCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSettingCompanyActionPerformed(evt);
            }
        });

        jButtonSales.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSales.setText("Sales");
        jButtonSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalesActionPerformed(evt);
            }
        });

        jButtonPurchases.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonPurchases.setText("Purchases");
        jButtonPurchases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPurchasesActionPerformed(evt);
            }
        });

        jButtonDrugDetails.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDrugDetails.setText("Drug Details");
        jButtonDrugDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDrugDetailsActionPerformed(evt);
            }
        });

        jButtonDrugs.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDrugs.setText("Drugs");
        jButtonDrugs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDrugsActionPerformed(evt);
            }
        });

        jButtonUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonUser.setText("User");
        jButtonUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUserActionPerformed(evt);
            }
        });

        jButtonAddUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAddUser.setText("Add User");
        jButtonAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddUserActionPerformed(evt);
            }
        });

        jButtonDeleteUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDeleteUser.setText("Delete User");
        jButtonDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteUserActionPerformed(evt);
            }
        });

        jButtonUpdateUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonUpdateUser.setText("Update User");
        jButtonUpdateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateUserActionPerformed(evt);
            }
        });

        jButtonAddDrug.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAddDrug.setText("Add Drug");
        jButtonAddDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddDrugActionPerformed(evt);
            }
        });

        jButtonDeleteDrug.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDeleteDrug.setText("Delete Drug");
        jButtonDeleteDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteDrugActionPerformed(evt);
            }
        });

        jButtonUpdateDrug.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonUpdateDrug.setText("Update Drug");

        jButtonSearchDrug.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSearchDrug.setText("Search Drug");
        jButtonSearchDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchDrugActionPerformed(evt);
            }
        });

        jButtonDrugsList.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDrugsList.setText("Drugs List");
        jButtonDrugsList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDrugsListActionPerformed(evt);
            }
        });

        jButtonMoveDrug.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonMoveDrug.setText("Move Drug");
        jButtonMoveDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMoveDrugActionPerformed(evt);
            }
        });

        jButtonCheckPlaces.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCheckPlaces.setText("Check Places");
        jButtonCheckPlaces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckPlacesActionPerformed(evt);
            }
        });

        jButtonEditPrices.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonEditPrices.setText("Edit Prices");
        jButtonEditPrices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditPricesActionPerformed(evt);
            }
        });

        jButtonExpireDrugs.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonExpireDrugs.setText("Expired Drugs");
        jButtonExpireDrugs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExpireDrugsActionPerformed(evt);
            }
        });

        jButtonRenewValidity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonRenewValidity.setText("Renew Validity");
        jButtonRenewValidity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRenewValidityActionPerformed(evt);
            }
        });

        jButtonAlmostFinished.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAlmostFinished.setText("Almost Finished");
        jButtonAlmostFinished.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlmostFinishedActionPerformed(evt);
            }
        });

        jButtonBuyDrugs.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonBuyDrugs.setText("Buy Drugs");
        jButtonBuyDrugs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuyDrugsActionPerformed(evt);
            }
        });

        jButtonUpdateDeals.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonUpdateDeals.setText("Update Deals");
        jButtonUpdateDeals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateDealsActionPerformed(evt);
            }
        });

        jButtonDealList.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDealList.setText("Deal List");
        jButtonDealList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDealListActionPerformed(evt);
            }
        });

        jButtonSalesBill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSalesBill.setText("Sales Bill");
        jButtonSalesBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalesBillActionPerformed(evt);
            }
        });

        jButtonShiftSales.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonShiftSales.setText("Shift Sales");
        jButtonShiftSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShiftSalesActionPerformed(evt);
            }
        });

        jButtonLoginDetails.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonLoginDetails.setText("Login Details");
        jButtonLoginDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginDetailsActionPerformed(evt);
            }
        });

        jButtonChangePassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonChangePassword.setText("Change Password");
        jButtonChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangePasswordActionPerformed(evt);
            }
        });

        jButtonLogout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonLogout.setText("Logout");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        jButtonAddCompany.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAddCompany.setText("Add Company");
        jButtonAddCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCompanyActionPerformed(evt);
            }
        });

        jButtonUpdateCompany.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonUpdateCompany.setText("Update Company");
        jButtonUpdateCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateCompanyActionPerformed(evt);
            }
        });

        jButtonDeleteCompany.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDeleteCompany.setText("Delete Company");
        jButtonDeleteCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteCompanyActionPerformed(evt);
            }
        });

        jButtonRecord.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonRecord.setText("Record");
        jButtonRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRecordActionPerformed(evt);
            }
        });

        jButtonSummary.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSummary.setText("Summary");
        jButtonSummary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSummaryActionPerformed(evt);
            }
        });

        jButtonDailyRecord.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDailyRecord.setText("Daily Record");

        jButtonClientList.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonClientList.setText("Client List");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonSettings)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonLoginDetails, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonChangePassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jButtonSettingCompany))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jButtonUpdateCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButtonAddCompany)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonSalesBill, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonShiftSales, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonSales)
                                .addGap(37, 37, 37))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonDeleteCompany)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonBuyDrugs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonUpdateDeals, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDealList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPurchases, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCheckPlaces, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEditPrices, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonRenewValidity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAlmostFinished, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonExpireDrugs, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonDrugDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonAddDrug, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDeleteDrug, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSearchDrug, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDrugsList, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButtonMoveDrug, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonUpdateDrug, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonDrugs, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonDeleteUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAddUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButtonSummary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonDailyRecord, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                .addComponent(jButtonClientList, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonRecord)
                                .addGap(43, 43, 43))))
                    .addComponent(jButtonUpdateUser))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSettings)
                            .addComponent(jButtonPurchases)
                            .addComponent(jButtonDrugDetails)
                            .addComponent(jButtonDrugs)
                            .addComponent(jButtonUser)
                            .addComponent(jButtonSales))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButtonAddUser)
                                .addGap(10, 10, 10)
                                .addComponent(jButtonDeleteUser)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonUpdateUser)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButtonCheckPlaces)
                                                .addGap(10, 10, 10)
                                                .addComponent(jButtonEditPrices)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButtonExpireDrugs))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButtonBuyDrugs)
                                                .addGap(10, 10, 10)
                                                .addComponent(jButtonUpdateDeals)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButtonDealList))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jButtonLoginDetails)
                                                    .addComponent(jButtonAddCompany))
                                                .addGap(10, 10, 10)
                                                .addComponent(jButtonChangePassword)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButtonLogout)))
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonRenewValidity)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButtonAlmostFinished))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonAddDrug)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButtonDeleteDrug)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonUpdateDrug)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonSearchDrug)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButtonMoveDrug)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonDrugsList)))
                                .addContainerGap(125, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonRecord)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonSummary)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonDailyRecord)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonClientList))
                            .addComponent(jButtonSettingCompany)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonSalesBill)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButtonShiftSales))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(jButtonUpdateCompany)))))
                        .addGap(23, 23, 23)
                        .addComponent(jButtonDeleteCompany)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUserActionPerformed
        // TODO add your handling code here:

        jButtonAddUser.setVisible(true);
        jButtonUpdateUser.setVisible(true);
        jButtonDeleteUser.setVisible(true);


    }//GEN-LAST:event_jButtonUserActionPerformed

    private void jButtonDrugsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDrugsActionPerformed
        // TODO add your handling code here:
        jButtonAddDrug.setVisible(true);
        jButtonDeleteDrug.setVisible(true);
        jButtonUpdateDrug.setVisible(true);
        jButtonSearchDrug.setVisible(true);
        jButtonMoveDrug.setVisible(true);
        jButtonDrugsList.setVisible(true);
    }//GEN-LAST:event_jButtonDrugsActionPerformed

    private void jButtonDrugDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDrugDetailsActionPerformed
        // TODO add your handling code here:
        jButtonCheckPlaces.setVisible(true);
        jButtonEditPrices.setVisible(true);
        jButtonExpireDrugs.setVisible(true);
        jButtonRenewValidity.setVisible(true);
        jButtonAlmostFinished.setVisible(true);
    }//GEN-LAST:event_jButtonDrugDetailsActionPerformed

    private void jButtonPurchasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPurchasesActionPerformed
        // TODO add your handling code here:
        jButtonBuyDrugs.setVisible(true);
        jButtonUpdateDeals.setVisible(true);
        jButtonDealList.setVisible(true);
    }//GEN-LAST:event_jButtonPurchasesActionPerformed

    private void jButtonSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalesActionPerformed
        // TODO add your handling code here:
        jButtonSalesBill.setVisible(true);
        jButtonShiftSales.setVisible(true);
    }//GEN-LAST:event_jButtonSalesActionPerformed

    private void jButtonSettingCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSettingCompanyActionPerformed
        // TODO add your handling code here:
        jButtonAddCompany.setVisible(true);
        jButtonUpdateCompany.setVisible(true);
        jButtonDeleteCompany.setVisible(true);
    }//GEN-LAST:event_jButtonSettingCompanyActionPerformed

    private void jButtonSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSettingsActionPerformed
        // TODO add your handling code here:
        jButtonLoginDetails.setVisible(true);
        jButtonChangePassword.setVisible(true);
        jButtonLogout.setVisible(true);
    }//GEN-LAST:event_jButtonSettingsActionPerformed

    private void jButtonRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRecordActionPerformed
        // TODO add your handling code here:
        jButtonSummary.setVisible(true);
        jButtonDailyRecord.setVisible(true);
        jButtonClientList.setVisible(true);
    }//GEN-LAST:event_jButtonRecordActionPerformed

    private void jButtonBuyDrugsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuyDrugsActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new BuyDrugsView().setVisible(true);
    }//GEN-LAST:event_jButtonBuyDrugsActionPerformed

    private void jButtonUpdateDealsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateDealsActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jButtonUpdateDealsActionPerformed

    private void jButtonDealListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDealListActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new DealListView().setVisible(true);
    }//GEN-LAST:event_jButtonDealListActionPerformed

    private void jButtonAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddUserActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new AddUserView().setVisible(true);
    }//GEN-LAST:event_jButtonAddUserActionPerformed

    private void jButtonUpdateCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateCompanyActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new UpdateCompanyView().setVisible(true);

    }//GEN-LAST:event_jButtonUpdateCompanyActionPerformed

    private void jButtonUpdateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateUserActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new UpdateUserView().setVisible(true);
    }//GEN-LAST:event_jButtonUpdateUserActionPerformed

    private void jButtonAddDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddDrugActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new AddDrugView().setVisible(true);
    }//GEN-LAST:event_jButtonAddDrugActionPerformed

    private void jButtonAddCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCompanyActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new AddCompanyView().setVisible(true);
    }//GEN-LAST:event_jButtonAddCompanyActionPerformed

    private void jButtonSummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSummaryActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new SummaryView().setVisible(true);
    }//GEN-LAST:event_jButtonSummaryActionPerformed

    private void jButtonSalesBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalesBillActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new SalesBillView().setVisible(true);
    }//GEN-LAST:event_jButtonSalesBillActionPerformed

    private void jButtonSearchDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchDrugActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new SearchDrugView().setVisible(true);
    }//GEN-LAST:event_jButtonSearchDrugActionPerformed

    private void jButtonMoveDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMoveDrugActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new MoveDrugView().setVisible(true);
    }//GEN-LAST:event_jButtonMoveDrugActionPerformed

    private void jButtonDrugsListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDrugsListActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new DrugListView().setVisible(true);
    }//GEN-LAST:event_jButtonDrugsListActionPerformed

    private void jButtonEditPricesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditPricesActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new EditPirceView().setVisible(true);
    }//GEN-LAST:event_jButtonEditPricesActionPerformed

    private void jButtonDeleteCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteCompanyActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new DeleteCompanyView().setVisible(true);
    }//GEN-LAST:event_jButtonDeleteCompanyActionPerformed

    private void jButtonCheckPlacesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckPlacesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCheckPlacesActionPerformed

    private void jButtonExpireDrugsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExpireDrugsActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ExpiredDrugsView().setVisible(true);
    }//GEN-LAST:event_jButtonExpireDrugsActionPerformed

    private void jButtonRenewValidityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRenewValidityActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonRenewValidityActionPerformed

    private void jButtonAlmostFinishedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlmostFinishedActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new AlmostFinishedDrugsView().setVisible(true);
    }//GEN-LAST:event_jButtonAlmostFinishedActionPerformed

    private void jButtonDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteUserActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new DeleteUserView().setVisible(true);
    }//GEN-LAST:event_jButtonDeleteUserActionPerformed

    private void jButtonInboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInboxActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new InboxView().setVisible(true);
    }//GEN-LAST:event_jButtonInboxActionPerformed

    private void jButtonLoginDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginDetailsActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new LoginDetailsView().setVisible(true);
    }//GEN-LAST:event_jButtonLoginDetailsActionPerformed

    private void jButtonChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangePasswordActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ChangePasswordView().setVisible(true);
    }//GEN-LAST:event_jButtonChangePasswordActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new LoginView().setVisible(true);
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jButtonShiftSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShiftSalesActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ShiftSalesBillView().setVisible(true);
    }//GEN-LAST:event_jButtonShiftSalesActionPerformed

    private void jButtonDeleteDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteDrugActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDeleteDrugActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministrationDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministrationDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministrationDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministrationDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministrationDashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddCompany;
    private javax.swing.JButton jButtonAddDrug;
    private javax.swing.JButton jButtonAddUser;
    private javax.swing.JButton jButtonAlmostFinished;
    private javax.swing.JButton jButtonBuyDrugs;
    private javax.swing.JButton jButtonChangePassword;
    private javax.swing.JButton jButtonCheckPlaces;
    private javax.swing.JButton jButtonClientList;
    private javax.swing.JButton jButtonDailyRecord;
    private javax.swing.JButton jButtonDealList;
    private javax.swing.JButton jButtonDeleteCompany;
    private javax.swing.JButton jButtonDeleteDrug;
    private javax.swing.JButton jButtonDeleteUser;
    private javax.swing.JButton jButtonDrugDetails;
    private javax.swing.JButton jButtonDrugs;
    private javax.swing.JButton jButtonDrugsList;
    private javax.swing.JButton jButtonEditPrices;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonExpireDrugs;
    private javax.swing.JButton jButtonInbox;
    private javax.swing.JButton jButtonLoginDetails;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonMoveDrug;
    private javax.swing.JButton jButtonPurchases;
    private javax.swing.JButton jButtonRecord;
    private javax.swing.JButton jButtonRenewValidity;
    private javax.swing.JButton jButtonSales;
    private javax.swing.JButton jButtonSalesBill;
    private javax.swing.JButton jButtonSearchDrug;
    private javax.swing.JButton jButtonSettingCompany;
    private javax.swing.JButton jButtonSettings;
    private javax.swing.JButton jButtonShiftSales;
    private javax.swing.JButton jButtonSummary;
    private javax.swing.JButton jButtonUpdateCompany;
    private javax.swing.JButton jButtonUpdateDeals;
    private javax.swing.JButton jButtonUpdateDrug;
    private javax.swing.JButton jButtonUpdateUser;
    private javax.swing.JButton jButtonUser;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelDay;
    private javax.swing.JLabel jLabelDay1;
    private javax.swing.JLabel jLabelTime;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
