/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import daoImp.BuyDrugDaoImp;
import daoImp.CompanyDaoImp;
import daoImp.DrugDaoImp;
import daoImp.LoginDaoImp;
import daoImp.SalesDaoImp;
import daoImp.SummaryDaoImp;
import daoImp.UserDaoImp;
import java.sql.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import pojo.Login;

/**
 *
 * @author shshe
 */
public class AdministrationDashBoard extends javax.swing.JFrame {

    /**
     * Creates new form AdministrationDashBoard
     */
    public AdministrationDashBoard() {

        initComponents();
        jLabelUser.setText("Logged in: " + LoginView.user_name);
        //user buttons
        jButtonAddUser.setVisible(false);
        jButtonUpdateUser.setVisible(false);
        jButtonDeleteUser.setVisible(false);
        //drug buttons
        jButtonAddDrug.setVisible(false);
        jButtonDeleteDrug.setVisible(false);
        jButtonUpdateDrug.setVisible(false);
        jButtonSearchDrug.setVisible(false);
        jButtonMoveDrug.setVisible(false);
        jButtonDrugsList.setVisible(false);

        //Drug details
        jButtonCheckPlaces.setVisible(false);
        jButtonEditPrices.setVisible(false);
        jButtonExpireDrugs.setVisible(false);
        jButtonRenewValidity.setVisible(false);
        jButtonAlmostFinished.setVisible(false);

        //purchases
        jButtonBuyDrugs.setVisible(false);
        jButtonUpdateDeals.setVisible(false);
        jButtonDealList.setVisible(false);

        //Sales
        jButtonSalesBill.setVisible(false);
        jButtonShiftSales.setVisible(false);

        //Company
        jButtonAddCompany.setVisible(false);
        jButtonUpdateCompany.setVisible(false);
        jButtonSalesTable.setVisible(false);

        //Settings
        jButtonLoginDetails.setVisible(false);
        jButtonChangePassword.setVisible(false);
        jButtonLogout.setVisible(false);

        //Record
        jButtonSummary.setVisible(false);
        jButtonDailyRecord.setVisible(false);
        jButtonClientList.setVisible(false);

        //inbox
        jButtonInbox.setVisible(false);
        //labels
        jLabelTime.setVisible(false);
        jLabelDay.setVisible(false);
        //automatically create tables
        //company
        new CompanyDaoImp().createTable();
        //buydrug table (purchase table)
        new BuyDrugDaoImp().createTable();

        //drug table
        new DrugDaoImp().createTable();

        //sales table
        new SalesDaoImp().createTable();
        //summary table
        new SummaryDaoImp().createTable();

        //user table
        new UserDaoImp().createTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelTime = new javax.swing.JLabel();
        jLabelDay = new javax.swing.JLabel();
        jButtonExit = new javax.swing.JButton();
        jLabelUser = new javax.swing.JLabel();
        jButtonInbox = new javax.swing.JButton();
        jButtonSettings = new javax.swing.JButton();
        jButtonCompany = new javax.swing.JButton();
        jButtonSales = new javax.swing.JButton();
        jButtonPurchases = new javax.swing.JButton();
        jButtonDrugDetails = new javax.swing.JButton();
        jButtonDrugs = new javax.swing.JButton();
        jButtonUser = new javax.swing.JButton();
        jButtonAddUser = new javax.swing.JButton();
        jButtonDeleteUser = new javax.swing.JButton();
        jButtonUpdateUser = new javax.swing.JButton();
        jButtonAddDrug = new javax.swing.JButton();
        jButtonDeleteDrug = new javax.swing.JButton();
        jButtonUpdateDrug = new javax.swing.JButton();
        jButtonSearchDrug = new javax.swing.JButton();
        jButtonDrugsList = new javax.swing.JButton();
        jButtonMoveDrug = new javax.swing.JButton();
        jButtonCheckPlaces = new javax.swing.JButton();
        jButtonEditPrices = new javax.swing.JButton();
        jButtonExpireDrugs = new javax.swing.JButton();
        jButtonRenewValidity = new javax.swing.JButton();
        jButtonAlmostFinished = new javax.swing.JButton();
        jButtonBuyDrugs = new javax.swing.JButton();
        jButtonUpdateDeals = new javax.swing.JButton();
        jButtonDealList = new javax.swing.JButton();
        jButtonSalesBill = new javax.swing.JButton();
        jButtonShiftSales = new javax.swing.JButton();
        jButtonLoginDetails = new javax.swing.JButton();
        jButtonChangePassword = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jButtonAddCompany = new javax.swing.JButton();
        jButtonUpdateCompany = new javax.swing.JButton();
        jButtonRecord = new javax.swing.JButton();
        jButtonSummary = new javax.swing.JButton();
        jButtonDailyRecord = new javax.swing.JButton();
        jButtonClientList = new javax.swing.JButton();
        jButtonSalesTable = new javax.swing.JButton();
        jButtonRefresh = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Pharmacy Management");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("(Administration)");

        jLabelTime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTime.setText("03:00:00");

        jLabelDay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelDay.setText("13-04-2019");

        jButtonExit.setBackground(new java.awt.Color(255, 0, 0));
        jButtonExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jLabelUser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelUser.setText("Logged in: Shetu");

        jButtonInbox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonInbox.setText("Inbox");
        jButtonInbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButtonExit)
                        .addGap(40, 40, 40)
                        .addComponent(jButtonInbox))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabelUser)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(75, 75, 75)))
                .addGap(154, 154, 154)
                .addComponent(jLabelTime)
                .addGap(62, 62, 62)
                .addComponent(jLabelDay)
                .addGap(199, 199, 199))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelUser)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonExit)
                                    .addComponent(jButtonInbox))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelTime, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelDay, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 21, Short.MAX_VALUE))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 110));

        jButtonSettings.setBackground(new java.awt.Color(0, 102, 204));
        jButtonSettings.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSettings.setText("Settings");
        jButtonSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSettingsActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 117, -1, -1));

        jButtonCompany.setBackground(new java.awt.Color(0, 102, 204));
        jButtonCompany.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCompany.setText("Company");
        jButtonCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCompanyActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 117, -1, -1));

        jButtonSales.setBackground(new java.awt.Color(0, 102, 204));
        jButtonSales.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSales.setText("Sales");
        jButtonSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 117, -1, -1));

        jButtonPurchases.setBackground(new java.awt.Color(0, 102, 204));
        jButtonPurchases.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonPurchases.setText("Purchases");
        jButtonPurchases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPurchasesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPurchases, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 117, 123, -1));

        jButtonDrugDetails.setBackground(new java.awt.Color(0, 102, 204));
        jButtonDrugDetails.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDrugDetails.setText("Drug Details");
        jButtonDrugDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDrugDetailsActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDrugDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 117, 131, -1));

        jButtonDrugs.setBackground(new java.awt.Color(0, 102, 204));
        jButtonDrugs.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDrugs.setText("Drugs");
        jButtonDrugs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDrugsActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDrugs, new org.netbeans.lib.awtextra.AbsoluteConstraints(796, 117, 109, -1));

        jButtonUser.setBackground(new java.awt.Color(0, 102, 204));
        jButtonUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonUser.setText("User");
        jButtonUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUserActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(955, 117, 111, -1));

        jButtonAddUser.setBackground(new java.awt.Color(0, 102, 204));
        jButtonAddUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAddUser.setText("Add User");
        jButtonAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddUserActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAddUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(955, 160, 111, -1));

        jButtonDeleteUser.setBackground(new java.awt.Color(0, 102, 204));
        jButtonDeleteUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDeleteUser.setText("Delete User");
        jButtonDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteUserActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDeleteUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(955, 195, -1, -1));

        jButtonUpdateUser.setBackground(new java.awt.Color(0, 102, 204));
        jButtonUpdateUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonUpdateUser.setText("Update User");
        jButtonUpdateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateUserActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonUpdateUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(955, 238, -1, -1));

        jButtonAddDrug.setBackground(new java.awt.Color(0, 102, 204));
        jButtonAddDrug.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAddDrug.setText("Add Drug");
        jButtonAddDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddDrugActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAddDrug, new org.netbeans.lib.awtextra.AbsoluteConstraints(796, 173, 121, -1));

        jButtonDeleteDrug.setBackground(new java.awt.Color(0, 102, 204));
        jButtonDeleteDrug.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDeleteDrug.setText("Delete Drug");
        jButtonDeleteDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteDrugActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDeleteDrug, new org.netbeans.lib.awtextra.AbsoluteConstraints(796, 208, 121, -1));

        jButtonUpdateDrug.setBackground(new java.awt.Color(0, 102, 204));
        jButtonUpdateDrug.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonUpdateDrug.setText("Update Drug");
        jButtonUpdateDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateDrugActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonUpdateDrug, new org.netbeans.lib.awtextra.AbsoluteConstraints(796, 251, -1, -1));

        jButtonSearchDrug.setBackground(new java.awt.Color(0, 102, 204));
        jButtonSearchDrug.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSearchDrug.setText("Search Drug");
        jButtonSearchDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchDrugActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSearchDrug, new org.netbeans.lib.awtextra.AbsoluteConstraints(796, 294, 121, -1));

        jButtonDrugsList.setBackground(new java.awt.Color(0, 102, 204));
        jButtonDrugsList.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDrugsList.setText("Drugs List");
        jButtonDrugsList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDrugsListActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDrugsList, new org.netbeans.lib.awtextra.AbsoluteConstraints(796, 360, 121, -1));

        jButtonMoveDrug.setBackground(new java.awt.Color(0, 102, 204));
        jButtonMoveDrug.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonMoveDrug.setText("Move Drug");
        jButtonMoveDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMoveDrugActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMoveDrug, new org.netbeans.lib.awtextra.AbsoluteConstraints(796, 329, 121, -1));

        jButtonCheckPlaces.setBackground(new java.awt.Color(0, 102, 204));
        jButtonCheckPlaces.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCheckPlaces.setText("Check Places");
        jButtonCheckPlaces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckPlacesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCheckPlaces, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 173, 141, -1));

        jButtonEditPrices.setBackground(new java.awt.Color(0, 102, 204));
        jButtonEditPrices.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonEditPrices.setText("Edit Prices");
        jButtonEditPrices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditPricesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditPrices, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 208, 141, -1));

        jButtonExpireDrugs.setBackground(new java.awt.Color(0, 102, 204));
        jButtonExpireDrugs.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonExpireDrugs.setText("Expired Drugs");
        jButtonExpireDrugs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExpireDrugsActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExpireDrugs, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 251, 140, -1));

        jButtonRenewValidity.setBackground(new java.awt.Color(0, 102, 204));
        jButtonRenewValidity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonRenewValidity.setText("Renew Validity");
        jButtonRenewValidity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRenewValidityActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRenewValidity, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 302, 141, -1));

        jButtonAlmostFinished.setBackground(new java.awt.Color(0, 102, 204));
        jButtonAlmostFinished.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAlmostFinished.setText("Almost Finished");
        jButtonAlmostFinished.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlmostFinishedActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAlmostFinished, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 337, -1, -1));

        jButtonBuyDrugs.setBackground(new java.awt.Color(0, 102, 204));
        jButtonBuyDrugs.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonBuyDrugs.setText("Buy Drugs");
        jButtonBuyDrugs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuyDrugsActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuyDrugs, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 173, 123, -1));

        jButtonUpdateDeals.setBackground(new java.awt.Color(0, 102, 204));
        jButtonUpdateDeals.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonUpdateDeals.setText("Update Deals");
        jButtonUpdateDeals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateDealsActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonUpdateDeals, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 216, -1, -1));

        jButtonDealList.setBackground(new java.awt.Color(0, 102, 204));
        jButtonDealList.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDealList.setText("Deal List");
        jButtonDealList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDealListActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDealList, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 259, 123, -1));

        jButtonSalesBill.setBackground(new java.awt.Color(0, 102, 204));
        jButtonSalesBill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSalesBill.setText("Sales Bill");
        jButtonSalesBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalesBillActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalesBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 173, 103, -1));

        jButtonShiftSales.setBackground(new java.awt.Color(0, 102, 204));
        jButtonShiftSales.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonShiftSales.setText("Shift Sales");
        jButtonShiftSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShiftSalesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonShiftSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 208, -1, -1));

        jButtonLoginDetails.setBackground(new java.awt.Color(0, 102, 204));
        jButtonLoginDetails.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonLoginDetails.setText("Login Details");
        jButtonLoginDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginDetailsActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLoginDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 173, 157, -1));

        jButtonChangePassword.setBackground(new java.awt.Color(0, 102, 204));
        jButtonChangePassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonChangePassword.setText("Change Password");
        jButtonChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangePasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonChangePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 216, -1, -1));

        jButtonLogout.setBackground(new java.awt.Color(0, 102, 204));
        jButtonLogout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonLogout.setText("Logout");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 259, 157, -1));

        jButtonAddCompany.setBackground(new java.awt.Color(0, 102, 204));
        jButtonAddCompany.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAddCompany.setText("Add Company");
        jButtonAddCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCompanyActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAddCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 153, -1, -1));

        jButtonUpdateCompany.setBackground(new java.awt.Color(0, 102, 204));
        jButtonUpdateCompany.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonUpdateCompany.setText("Update Company");
        jButtonUpdateCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateCompanyActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonUpdateCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 189, 147, -1));

        jButtonRecord.setBackground(new java.awt.Color(0, 102, 204));
        jButtonRecord.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonRecord.setText("Record");
        jButtonRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRecordActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(1117, 117, -1, -1));

        jButtonSummary.setBackground(new java.awt.Color(0, 102, 204));
        jButtonSummary.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSummary.setText("Summary");
        jButtonSummary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSummaryActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSummary, new org.netbeans.lib.awtextra.AbsoluteConstraints(1084, 153, 157, -1));

        jButtonDailyRecord.setBackground(new java.awt.Color(0, 102, 204));
        jButtonDailyRecord.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDailyRecord.setText("Daily Record");
        getContentPane().add(jButtonDailyRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(1084, 189, 157, -1));

        jButtonClientList.setBackground(new java.awt.Color(0, 102, 204));
        jButtonClientList.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonClientList.setText("Client List");
        getContentPane().add(jButtonClientList, new org.netbeans.lib.awtextra.AbsoluteConstraints(1084, 225, 157, -1));

        jButtonSalesTable.setBackground(new java.awt.Color(0, 102, 204));
        jButtonSalesTable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSalesTable.setText("Sales Table");
        jButtonSalesTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalesTableActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalesTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 244, -1, -1));

        jButtonRefresh.setBackground(new java.awt.Color(0, 153, 102));
        jButtonRefresh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonRefresh.setText("Refresh");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 157, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/88775440-medical-background-medical-care-health-care-vector-medicine-illustration.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1250, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
//        // TODO add your handling code here:
//        Date date = new Date(System.currentTimeMillis());
//        SimpleDateFormat formatter = new SimpleDateFormat("HH:mm:ss");
//
//        String logout_time = formatter.format(date);
//        String duration = "not yet!";
//        ///for duration
//
//        /////////////////////////
//        Login login = new Login(LoginView.login_time, logout_time, duration);
//        new LoginDaoImp().update(login);
//        JOptionPane.showMessageDialog(null, "login table is updated successfully!");
        System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUserActionPerformed
        // TODO add your handling code here:

        jButtonAddUser.setVisible(true);
        jButtonUpdateUser.setVisible(true);
        jButtonDeleteUser.setVisible(true);
        jButtonUser.setEnabled(false);

    }//GEN-LAST:event_jButtonUserActionPerformed

    private void jButtonDrugsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDrugsActionPerformed
        // TODO add your handling code here:
        jButtonAddDrug.setVisible(true);
        jButtonDeleteDrug.setVisible(true);
        jButtonUpdateDrug.setVisible(true);
        jButtonSearchDrug.setVisible(true);
        jButtonMoveDrug.setVisible(true);
        jButtonDrugsList.setVisible(true);
        jButtonDrugs.setEnabled(false);
    }//GEN-LAST:event_jButtonDrugsActionPerformed

    private void jButtonDrugDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDrugDetailsActionPerformed
        // TODO add your handling code here:
        jButtonCheckPlaces.setVisible(true);
        jButtonEditPrices.setVisible(true);
        jButtonExpireDrugs.setVisible(true);
        jButtonRenewValidity.setVisible(true);
        jButtonAlmostFinished.setVisible(true);
        jButtonDrugDetails.setEnabled(false);
    }//GEN-LAST:event_jButtonDrugDetailsActionPerformed

    private void jButtonPurchasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPurchasesActionPerformed
        // TODO add your handling code here:
        jButtonBuyDrugs.setVisible(true);
        jButtonUpdateDeals.setVisible(true);
        jButtonDealList.setVisible(true);
        jButtonPurchases.setEnabled(false);
    }//GEN-LAST:event_jButtonPurchasesActionPerformed

    private void jButtonSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalesActionPerformed
        // TODO add your handling code here:
        jButtonSalesBill.setVisible(true);
        jButtonShiftSales.setVisible(true);
        jButtonSalesTable.setVisible(true);
        jButtonSales.setEnabled(false);
    }//GEN-LAST:event_jButtonSalesActionPerformed

    private void jButtonCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCompanyActionPerformed
        // TODO add your handling code here:
        jButtonAddCompany.setVisible(true);
        jButtonUpdateCompany.setVisible(true);

        jButtonCompany.setEnabled(false);

    }//GEN-LAST:event_jButtonCompanyActionPerformed

    private void jButtonSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSettingsActionPerformed
        // TODO add your handling code here:
        jButtonLoginDetails.setVisible(true);
        jButtonChangePassword.setVisible(true);
        jButtonLogout.setVisible(true);
        jButtonSettings.setEnabled(false);
    }//GEN-LAST:event_jButtonSettingsActionPerformed

    private void jButtonRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRecordActionPerformed
        // TODO add your handling code here:
        jButtonSummary.setVisible(true);
        jButtonDailyRecord.setVisible(true);
        jButtonClientList.setVisible(true);
        jButtonRecord.setEnabled(false);
    }//GEN-LAST:event_jButtonRecordActionPerformed

    private void jButtonBuyDrugsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuyDrugsActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new BuyDrugsView().setVisible(true);
    }//GEN-LAST:event_jButtonBuyDrugsActionPerformed

    private void jButtonUpdateDealsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateDealsActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new UpdateDeals().setVisible(true);

    }//GEN-LAST:event_jButtonUpdateDealsActionPerformed

    private void jButtonDealListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDealListActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new DealListView().setVisible(true);
    }//GEN-LAST:event_jButtonDealListActionPerformed

    private void jButtonAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddUserActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new AddUserView().setVisible(true);
    }//GEN-LAST:event_jButtonAddUserActionPerformed

    private void jButtonUpdateCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateCompanyActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new UpdateCompanyView().setVisible(true);

    }//GEN-LAST:event_jButtonUpdateCompanyActionPerformed

    private void jButtonUpdateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateUserActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new UpdateUserView().setVisible(true);
    }//GEN-LAST:event_jButtonUpdateUserActionPerformed

    private void jButtonAddDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddDrugActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new AddDrugView().setVisible(true);
    }//GEN-LAST:event_jButtonAddDrugActionPerformed

    private void jButtonAddCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCompanyActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new AddCompanyView().setVisible(true);
    }//GEN-LAST:event_jButtonAddCompanyActionPerformed

    private void jButtonSummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSummaryActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new SummaryView().setVisible(true);
    }//GEN-LAST:event_jButtonSummaryActionPerformed

    private void jButtonSalesBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalesBillActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new SalesBillView().setVisible(true);
    }//GEN-LAST:event_jButtonSalesBillActionPerformed

    private void jButtonSearchDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchDrugActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new SearchDrugView().setVisible(true);
    }//GEN-LAST:event_jButtonSearchDrugActionPerformed

    private void jButtonMoveDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMoveDrugActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new MoveDrugView().setVisible(true);
    }//GEN-LAST:event_jButtonMoveDrugActionPerformed

    private void jButtonDrugsListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDrugsListActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new DrugListView().setVisible(true);
    }//GEN-LAST:event_jButtonDrugsListActionPerformed

    private void jButtonEditPricesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditPricesActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new EditPirceView().setVisible(true);
    }//GEN-LAST:event_jButtonEditPricesActionPerformed

    private void jButtonCheckPlacesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckPlacesActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new CheckPlacesView().setVisible(true);
    }//GEN-LAST:event_jButtonCheckPlacesActionPerformed

    private void jButtonExpireDrugsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExpireDrugsActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ExpiredDrugsView().setVisible(true);
    }//GEN-LAST:event_jButtonExpireDrugsActionPerformed

    private void jButtonRenewValidityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRenewValidityActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new RenewValidityView().setVisible(true);
    }//GEN-LAST:event_jButtonRenewValidityActionPerformed

    private void jButtonAlmostFinishedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlmostFinishedActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new AlmostFinishedDrugsView().setVisible(true);
    }//GEN-LAST:event_jButtonAlmostFinishedActionPerformed

    private void jButtonDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteUserActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new DeleteUserView().setVisible(true);
    }//GEN-LAST:event_jButtonDeleteUserActionPerformed

    private void jButtonInboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInboxActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new InboxView().setVisible(true);
    }//GEN-LAST:event_jButtonInboxActionPerformed

    private void jButtonLoginDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginDetailsActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new LoginDetailsView().setVisible(true);
    }//GEN-LAST:event_jButtonLoginDetailsActionPerformed

    private void jButtonChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangePasswordActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ChangePasswordView().setVisible(true);
    }//GEN-LAST:event_jButtonChangePasswordActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new LoginView().setVisible(true);
        Date date = new Date(System.currentTimeMillis());
        SimpleDateFormat formatter = new SimpleDateFormat("HH:mm:ss");

        String logout_time = formatter.format(date);
        String duration = "not yet!";
        ///for duration

        /////////////////////////
        Login login = new Login(LoginView.login_time, logout_time, duration);
        new LoginDaoImp().update(login);
        JOptionPane.showMessageDialog(null, "login table is updated successfully!");
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jButtonShiftSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShiftSalesActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ShiftSales().setVisible(true);
    }//GEN-LAST:event_jButtonShiftSalesActionPerformed

    private void jButtonDeleteDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteDrugActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new DeleteDrugView().setVisible(true);
    }//GEN-LAST:event_jButtonDeleteDrugActionPerformed

    private void jButtonSalesTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalesTableActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new SalesTableView().setVisible(true);
    }//GEN-LAST:event_jButtonSalesTableActionPerformed

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        // TODO add your handling code here:
        //all the central buttons
        jButtonSettings.setEnabled(true);
        jButtonCompany.setEnabled(true);
        jButtonSales.setEnabled(true);
        jButtonPurchases.setEnabled(true);
        jButtonDrugDetails.setEnabled(true);
        jButtonDrugs.setEnabled(true);
        jButtonUser.setEnabled(true);
        jButtonRecord.setEnabled(true);

        //all the subordinate buttons
        jButtonAddUser.setVisible(false);
        jButtonUpdateUser.setVisible(false);
        jButtonDeleteUser.setVisible(false);
        //drug buttons
        jButtonAddDrug.setVisible(false);
        jButtonDeleteDrug.setVisible(false);
        jButtonUpdateDrug.setVisible(false);
        jButtonSearchDrug.setVisible(false);
        jButtonMoveDrug.setVisible(false);
        jButtonDrugsList.setVisible(false);

        //Drug details
        jButtonCheckPlaces.setVisible(false);
        jButtonEditPrices.setVisible(false);
        jButtonExpireDrugs.setVisible(false);
        jButtonRenewValidity.setVisible(false);
        jButtonAlmostFinished.setVisible(false);

        //purchases
        jButtonBuyDrugs.setVisible(false);
        jButtonUpdateDeals.setVisible(false);
        jButtonDealList.setVisible(false);

        //Sales
        jButtonSalesBill.setVisible(false);
        jButtonShiftSales.setVisible(false);

        //Company
        jButtonAddCompany.setVisible(false);
        jButtonUpdateCompany.setVisible(false);
        jButtonSalesTable.setVisible(false);

        //Settings
        jButtonLoginDetails.setVisible(false);
        jButtonChangePassword.setVisible(false);
        jButtonLogout.setVisible(false);

        //Record
        jButtonSummary.setVisible(false);
        jButtonDailyRecord.setVisible(false);
        jButtonClientList.setVisible(false);
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void jButtonUpdateDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateDrugActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new UpdateDrugView().setVisible(true);
    }//GEN-LAST:event_jButtonUpdateDrugActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministrationDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministrationDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministrationDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministrationDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministrationDashBoard().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddCompany;
    private javax.swing.JButton jButtonAddDrug;
    private javax.swing.JButton jButtonAddUser;
    private javax.swing.JButton jButtonAlmostFinished;
    private javax.swing.JButton jButtonBuyDrugs;
    private javax.swing.JButton jButtonChangePassword;
    private javax.swing.JButton jButtonCheckPlaces;
    private javax.swing.JButton jButtonClientList;
    private javax.swing.JButton jButtonCompany;
    private javax.swing.JButton jButtonDailyRecord;
    private javax.swing.JButton jButtonDealList;
    private javax.swing.JButton jButtonDeleteDrug;
    private javax.swing.JButton jButtonDeleteUser;
    private javax.swing.JButton jButtonDrugDetails;
    private javax.swing.JButton jButtonDrugs;
    private javax.swing.JButton jButtonDrugsList;
    private javax.swing.JButton jButtonEditPrices;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonExpireDrugs;
    private javax.swing.JButton jButtonInbox;
    private javax.swing.JButton jButtonLoginDetails;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonMoveDrug;
    private javax.swing.JButton jButtonPurchases;
    private javax.swing.JButton jButtonRecord;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JButton jButtonRenewValidity;
    private javax.swing.JButton jButtonSales;
    private javax.swing.JButton jButtonSalesBill;
    private javax.swing.JButton jButtonSalesTable;
    private javax.swing.JButton jButtonSearchDrug;
    private javax.swing.JButton jButtonSettings;
    private javax.swing.JButton jButtonShiftSales;
    private javax.swing.JButton jButtonSummary;
    private javax.swing.JButton jButtonUpdateCompany;
    private javax.swing.JButton jButtonUpdateDeals;
    private javax.swing.JButton jButtonUpdateDrug;
    private javax.swing.JButton jButtonUpdateUser;
    private javax.swing.JButton jButtonUser;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelDay;
    private javax.swing.JLabel jLabelTime;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
