/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import daoImp.CompanyDaoImp;
import daoImp.SalesDaoImp;
import daoImp.SummaryDaoImp;
import daoImp.UserDaoImp;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.Company;
import pojo.Sales;
import pojo.Summary;
import pojo.User;

/**
 *
 * @author shshe
 */
public class SalesBillView extends javax.swing.JFrame {

    /**
     * Creates new form SearchDrugView
     */
    public SalesBillView() {
        initComponents();
    }
    static double total = 0.0;

    public void diplayDataIntoBillTable() {
        String name = jTextFieldDrugName.getText().trim();
        int quantity = Integer.parseInt(jTextFieldQuantity.getText());
        Date date = new Date(System.currentTimeMillis());
        SimpleDateFormat formatter = new SimpleDateFormat("HH:mm:ss");
        String time = formatter.format(date);
        /*Calendar c = Calendar.getInstance();
c.setTimeInMillis(System.currentTimeMillis());

String date = c.get(Calendar.YEAR)+"-"+c.get(Calendar.MONTH)+"-"+c.get(Calendar.DAY_OF_MONTH);
String time = c.get(Calendar.HOUR_OF_DAY)+":"+c.get(Calendar.MINUTE)+":"+c.get(Calendar.SECOND);

System.out.println(date + " " + time);*/

        DefaultTableModel model = (DefaultTableModel) jTableSalesBill.getModel();
        Summary sum = new SummaryDaoImp().getSummaryByDrugName(name);
        Object[] cols = new Object[10];
        for (int i = 0; i < 1; i++) {
            cols[0] = sum.getDrug_barcode();
            cols[1] = sum.getDrug_name();
            cols[2] = sum.getDrug_type();
            cols[3] = sum.getDrug_dose();
            cols[4] = quantity;
            cols[5] = sum.getSell_price();
            cols[6] = sum.getSell_price() * quantity;
            Company com = new CompanyDaoImp().getCompanyById(sum.getCompany().getCompany_id());
            cols[7] = com.getCompany_name();
            cols[8] = date;
            cols[9] = time;
            total += sum.getSell_price() * quantity;
            model.addRow(cols);
        }
//        //list 
//        List<Sales> list = new SalesDaoImp().getSales();
//        for (int i = 0; i < 1; i++) {
//            cols[0] = productName;
//            cols[1] = quantity;
//            cols[2] = productPrice;
//            cols[3] = quantity * productPrice;
//            model.addRow(cols);
//        }
//
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldDrugName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldBarcode = new javax.swing.JTextField();
        jButtonAddToCart = new javax.swing.JButton();
        jButtonBill = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jButtonClear = new javax.swing.JButton();
        jButtonCancel1 = new javax.swing.JButton();
        jButtonPrint = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldQuantity = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableSalesBill = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableFromSummary = new javax.swing.JTable();
        jButtonDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Sales Bill Form");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(436, 436, 436)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Drug Name:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 30, -1, -1));

        jTextFieldDrugName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldDrugName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldDrugNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldDrugNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDrugNameKeyTyped(evt);
            }
        });
        jPanel2.add(jTextFieldDrugName, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 26, 151, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Barcode: ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 30, -1, -1));

        jTextFieldBarcode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(jTextFieldBarcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 27, 143, -1));

        jButtonAddToCart.setBackground(new java.awt.Color(0, 102, 102));
        jButtonAddToCart.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAddToCart.setText("Add To Cart");
        jButtonAddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddToCartActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAddToCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(1065, 26, -1, -1));

        jButtonBill.setBackground(new java.awt.Color(0, 102, 102));
        jButtonBill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonBill.setText("Bill");
        jButtonBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBillActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 430, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Total");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 432, -1, -1));

        jLabelTotal.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelTotal.setText("00.0$");
        jPanel2.add(jLabelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 410, -1, -1));

        jButtonClear.setBackground(new java.awt.Color(0, 102, 102));
        jButtonClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 430, -1, -1));

        jButtonCancel1.setBackground(new java.awt.Color(0, 102, 102));
        jButtonCancel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCancel1.setText("Cancel");
        jButtonCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancel1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCancel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1097, 428, -1, -1));

        jButtonPrint.setBackground(new java.awt.Color(0, 102, 102));
        jButtonPrint.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonPrint.setText("Print");
        jPanel2.add(jButtonPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 428, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Quantity:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 29, -1, -1));

        jTextFieldQuantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(jTextFieldQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 26, 151, -1));

        jTableSalesBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Barcode", "Name", "Type", "Dose", "Quantity", "Price", "Amount", "Company", "Date", "Time"
            }
        ));
        jScrollPane2.setViewportView(jTableSalesBill);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 284, 1160, 130));

        jTableFromSummary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug Id", "Name", "Type", "Barcode", "Dose", "Group", "Buy_Price", "Sell_Price", "Com_Name", "Pro_Date", "Ex_ Date", "Ex_Time", "Validity ", "Tax", "Place", "Total_Qty", "Available_Qty", "Sold_Qty"
            }
        ));
        jTableFromSummary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableFromSummaryKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(jTableFromSummary);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 69, 1160, 170));

        jButtonDelete.setBackground(new java.awt.Color(0, 102, 102));
        jButtonDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 430, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1214, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTableSalesBill.getModel();
        model.setRowCount(0);
        jLabelTotal.setText("0.00");
        total = 0.00;

    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancel1ActionPerformed
        // TODO add your handling code here:
        User user = new UserDaoImp().getUserByUserName(LoginView.user_name);
        if (user.getRoleName().equalsIgnoreCase("admin")) {
            this.setVisible(false);
            new AdministrationDashBoard().setVisible(true);
        } else if (user.getRoleName().equalsIgnoreCase("employee")) {
            this.setVisible(false);
            new EmployeeDashBoard().setVisible(true);
        }
    }//GEN-LAST:event_jButtonCancel1ActionPerformed

    private void jTextFieldDrugNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDrugNameKeyTyped


    }//GEN-LAST:event_jTextFieldDrugNameKeyTyped

    private void jTableFromSummaryKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableFromSummaryKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTableFromSummaryKeyPressed

    private void jTextFieldDrugNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDrugNameKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            // TODO add your handling code here:
            // TODO add your handling code here:
            //        String name = jTextFieldDrugName.getText().trim();
            String name = jTextFieldDrugName.getText().trim();

            DefaultTableModel model = (DefaultTableModel) jTableFromSummary.getModel();
            model.setRowCount(0);
            Summary sum = new SummaryDaoImp().getSummaryByDrugName(name);

            Object[] cols = new Object[18];
            for (int i = 0; i < 1; i++) {
                cols[0] = sum.getDrug_id();
                cols[1] = sum.getDrug_name();
                cols[2] = sum.getDrug_type();
                cols[3] = sum.getDrug_barcode();
                cols[4] = sum.getDrug_dose();
                cols[5] = sum.getDrug_group();
                cols[6] = sum.getBuy_price();
                cols[7] = sum.getSell_price();
                Company com = new CompanyDaoImp().getCompanyById(sum.getCompany().getCompany_id());
                cols[8] = com.getCompany_name();
                cols[9] = sum.getProduction_date();
                cols[10] = sum.getExpire_date();
                cols[11] = sum.getExpire_time();
                cols[12] = sum.getValidity();
                cols[13] = sum.getDrug_tax();
                cols[14] = sum.getDrug_place();
                cols[15] = sum.getTotal_qty();
                cols[16] = sum.getAvailable_qty();
                cols[17] = sum.getSold_qty();
                model.addRow(cols);
            }
        }
    }//GEN-LAST:event_jTextFieldDrugNameKeyPressed

    private void jButtonAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddToCartActionPerformed
        // TODO add your handling code here:
        diplayDataIntoBillTable();
        jLabelTotal.setText(String.valueOf(total));
    }//GEN-LAST:event_jButtonAddToCartActionPerformed

    private void jButtonBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBillActionPerformed
        // TODO add your handling code here:

        DefaultTableModel model = (DefaultTableModel) jTableSalesBill.getModel();
        int rowCount = model.getRowCount();

        for (int i = 0; i < rowCount; i++) {

///////////////////////////////////////////////////////////////////
            String name = model.getValueAt(i, 1).toString();
            int qty = Integer.parseInt(model.getValueAt(i, 4).toString());
            double total_gain = Double.parseDouble(model.getValueAt(i, 6).toString());
            int total_qty1 = (new SummaryDaoImp().getSummaryByDrugName(name).getTotal_qty());
            int available_qty1 = (new SummaryDaoImp().getSummaryByDrugName(name).getAvailable_qty()) - qty;
            int sold_qty1 = (new SummaryDaoImp().getSummaryByDrugName(name).getSold_qty()) + qty;
            Summary sum1 = new Summary(name, total_qty1, available_qty1, sold_qty1);
            try {
                new SummaryDaoImp().updateSales(sum1);
                JOptionPane.showMessageDialog(null, "Data is updated successfully into summary table!");
            } catch (NullPointerException e) {
                JOptionPane.showMessageDialog(null, "Error!");
            }
            //insert into sales table

//            //all the fields
//            //qty
//            //name 
            String drug_type = new SummaryDaoImp().getSummaryByDrugName(name).getDrug_type();
            String drug_barcode = new SummaryDaoImp().getSummaryByDrugName(name).getDrug_barcode();
            String drug_dose = new SummaryDaoImp().getSummaryByDrugName(name).getDrug_dose();
            String drug_group = new SummaryDaoImp().getSummaryByDrugName(name).getDrug_group();
            Double buy_price = new SummaryDaoImp().getSummaryByDrugName(name).getBuy_price();
            Double sell_price = new SummaryDaoImp().getSummaryByDrugName(name).getSell_price();

            String com_name = model.getValueAt(i, 7).toString();

            Date pro_date = new SummaryDaoImp().getSummaryByDrugName(name).getProduction_date();
            Date exp_date = new SummaryDaoImp().getSummaryByDrugName(name).getExpire_date();
            String exp_time = new SummaryDaoImp().getSummaryByDrugName(name).getExpire_time();
            String validity = new SummaryDaoImp().getSummaryByDrugName(name).getValidity();
            Double drug_tax = new SummaryDaoImp().getSummaryByDrugName(name).getDrug_tax();
            String drug_place = new SummaryDaoImp().getSummaryByDrugName(name).getDrug_place();
            int total_qty = new SummaryDaoImp().getSummaryByDrugName(name).getTotal_qty();
            int available_qty2 = (new SummaryDaoImp().getSummaryByDrugName(name).getAvailable_qty());
            int sold_qty2 = (new SummaryDaoImp().getSummaryByDrugName(name).getSold_qty());
//            //date and time
            Date sell_date = new Date(System.currentTimeMillis());
            SimpleDateFormat formatter = new SimpleDateFormat("HH:mm:ss");
            String sell_time = formatter.format(sell_date);
            String username = LoginView.user_name;

//  
            Sales s = new Sales(name, drug_type, drug_barcode, drug_dose, drug_group, buy_price, sell_price, com_name, pro_date, exp_date, exp_time, validity, drug_tax, drug_place, total_qty, available_qty2, sold_qty2, sell_date, sell_time, username, total_gain);
            new SalesDaoImp().insert(s);
//            JOptionPane.showMessageDialog(null, "Data is inserted successfully into Sales Table!");
            total = 0.0;
            jLabelTotal.setText(String.valueOf(total));
        }

        model.setRowCount(0);
        JOptionPane.showMessageDialog(null, rowCount + " products have been sold!");


    }//GEN-LAST:event_jButtonBillActionPerformed

    private void jTextFieldDrugNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDrugNameKeyReleased
//        // TODO add your handling code here:
//        // TODO add your handling code here:
//        //        String name = jTextFieldDrugName.getText().trim();
//        String name = jTextFieldDrugName.getText().trim();
//
//        DefaultTableModel model = (DefaultTableModel) jTableFromSummary.getModel();
//        model.setRowCount(0);
//        Summary sum = new SummaryDaoImp().getSummaryByDrugName(name);
//
//        Object[] cols = new Object[18];
//        for (int i = 0; i < 1; i++) {
//            cols[0] = sum.getDrug_id();
//            cols[1] = sum.getDrug_name();
//            cols[2] = sum.getDrug_type();
//            cols[3] = sum.getDrug_barcode();
//            cols[4] = sum.getDrug_dose();
//            cols[5] = sum.getDrug_group();
//            cols[6] = sum.getBuy_price();
//            cols[7] = sum.getSell_price();
//            Company com = new CompanyDaoImp().getCompanyById(sum.getCompany().getCompany_id());
//            cols[8] = com.getCompany_name();
//            cols[9] = sum.getProduction_date();
//            cols[10] = sum.getExpire_date();
//            cols[11] = sum.getExpire_time();
//            cols[12] = sum.getValidity();
//            cols[13] = sum.getDrug_tax();
//            cols[14] = sum.getDrug_place();
//            cols[15] = sum.getTotal_qty();
//            cols[16] = sum.getAvailable_qty();
//            cols[17] = sum.getSold_qty();
//            model.addRow(cols);
//        }

    }//GEN-LAST:event_jTextFieldDrugNameKeyReleased

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesBillView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesBillView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesBillView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesBillView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesBillView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddToCart;
    private javax.swing.JButton jButtonBill;
    private javax.swing.JButton jButtonCancel1;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonPrint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableFromSummary;
    private javax.swing.JTable jTableSalesBill;
    private javax.swing.JTextField jTextFieldBarcode;
    private javax.swing.JTextField jTextFieldDrugName;
    private javax.swing.JTextField jTextFieldQuantity;
    // End of variables declaration//GEN-END:variables
}
