/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Date_19_02_2019.Evidence;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class StudentView extends javax.swing.JFrame {

    /**
     * Creates new form StudentView
     */
    public StudentView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlblID = new javax.swing.JLabel();
        jtxtID = new javax.swing.JTextField();
        jtxtName = new javax.swing.JTextField();
        jlblName = new javax.swing.JLabel();
        jtxtAge = new javax.swing.JTextField();
        jlblID2 = new javax.swing.JLabel();
        jtxtEmail = new javax.swing.JTextField();
        jlblID3 = new javax.swing.JLabel();
        jtxtComment = new javax.swing.JTextField();
        jlblID4 = new javax.swing.JLabel();
        jlblID5 = new javax.swing.JLabel();
        jlblID6 = new javax.swing.JLabel();
        jlblID7 = new javax.swing.JLabel();
        jradioFemale = new javax.swing.JRadioButton();
        jradioMale = new javax.swing.JRadioButton();
        jcheckJS = new javax.swing.JCheckBox();
        jcheckCoreJava = new javax.swing.JCheckBox();
        jcheckHTML = new javax.swing.JCheckBox();
        jcmbRound = new javax.swing.JComboBox<>();
        jButtonAddToTableAndWriteToFile = new javax.swing.JButton();
        jButtonClearForm = new javax.swing.JButton();
        jButtonClearTable = new javax.swing.JButton();
        jButtonReadFromFile = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDisplay = new javax.swing.JTable();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Student Information");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jLabel1)
                .addContainerGap(198, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 710, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlblID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlblID.setText("ID:");

        jtxtID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jtxtName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jlblName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlblName.setText("Name:");

        jtxtAge.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jlblID2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlblID2.setText("Age:");

        jtxtEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jlblID3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlblID3.setText("Email:");

        jtxtComment.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jlblID4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlblID4.setText("Comments:");

        jlblID5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlblID5.setText("Round:");

        jlblID6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlblID6.setText("Completed Courses:");

        jlblID7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlblID7.setText("Gender:");

        buttonGroup1.add(jradioFemale);
        jradioFemale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jradioFemale.setText("Female");

        buttonGroup1.add(jradioMale);
        jradioMale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jradioMale.setText("Male");
        jradioMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradioMaleActionPerformed(evt);
            }
        });

        jcheckJS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcheckJS.setText("JS");

        jcheckCoreJava.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcheckCoreJava.setText("Core Java");

        jcheckHTML.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcheckHTML.setText("HTML");

        jcmbRound.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcmbRound.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select A Round", "Round 37", "Round 38", "Round 39", "Round 40" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblID3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblID, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jlblID2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlblID7, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblID6, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblID5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblID4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jcheckHTML)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcheckJS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcheckCoreJava))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jradioMale, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jradioFemale))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jcmbRound, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                        .addComponent(jtxtAge, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                        .addComponent(jtxtName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                        .addComponent(jtxtID, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jtxtComment, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(231, 231, 231))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblID)
                    .addComponent(jtxtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblID2)
                    .addComponent(jtxtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblID3)
                    .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jlblID7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jradioFemale)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblID6)
                            .addComponent(jcheckJS)
                            .addComponent(jcheckCoreJava)
                            .addComponent(jcheckHTML)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jradioMale)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblID5)
                    .addComponent(jcmbRound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jlblID4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jtxtComment, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 520, 330));

        jButtonAddToTableAndWriteToFile.setText("Add To Table And Write To File");
        jButtonAddToTableAndWriteToFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddToTableAndWriteToFileActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAddToTableAndWriteToFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 190, -1));

        jButtonClearForm.setText("Clear Form");
        jButtonClearForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearFormActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonClearForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, -1, -1));

        jButtonClearTable.setText("Clear Table");
        jButtonClearTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearTableActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonClearTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, -1, -1));

        jButtonReadFromFile.setText("Read From FIle");
        getContentPane().add(jButtonReadFromFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, -1, -1));

        jTableDisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        jScrollPane1.setViewportView(jTableDisplay);
        if (jTableDisplay.getColumnModel().getColumnCount() > 0) {
            jTableDisplay.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 660, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jradioMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradioMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jradioMaleActionPerformed

    private void jButtonAddToTableAndWriteToFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddToTableAndWriteToFileActionPerformed
        int id = Integer.parseInt(jtxtID.getText());
        String name = jtxtName.getText();
        int age = Integer.parseInt(jtxtAge.getText());
        String email = jtxtEmail.getText();
        String gender = "";
        if(jradioMale.isSelected()== true){
        gender+=jradioMale.getText();
        }
        else if(jradioFemale.isSelected()== true){
        gender+=jradioFemale.getText();
        }
        String ccourse = "";
        if(jcheckHTML.isSelected()== true){
        ccourse+=jcheckHTML.getText()+" ";
        }
         if(jcheckJS.isSelected()== true){
        ccourse+=jcheckJS.getText()+" ";
        }
          if(jcheckCoreJava.isSelected()== true){
        ccourse+=jcheckCoreJava.getText()+" ";
        }
          String round = jcmbRound.getItemAt(jcmbRound.getSelectedIndex());
          String comment = jtxtComment.getText();
          String result = id+"\n"+name+"\n"+age+"\n"+email+"\n"+gender+"\n"+ccourse+"\n"+comment;
          
          DefaultTableModel model = (DefaultTableModel)jTableDisplay.getModel();
          Object[] row = new Object[9]; //This row must be Object type
          row[0] = id;
          row[1] = name;
          row[2] = age;
          row[3] = email;
          row[4] = gender;
          row[5] = ccourse;
          row[6] = round;
          row[7] = comment;
          model.addRow(row);
    }//GEN-LAST:event_jButtonAddToTableAndWriteToFileActionPerformed

    private void jButtonClearFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearFormActionPerformed
     jtxtID.setText("");
     jtxtAge.setText("");
     jtxtEmail.setText("");
     buttonGroup1.clearSelection();
     jcheckHTML.setSelected(false);
     jcheckJS.setSelected(false);
     jcheckCoreJava.setSelected(false);
     jcmbRound.setSelectedIndex(0);
     jtxtComment.setText("");
    }//GEN-LAST:event_jButtonClearFormActionPerformed

    private void jButtonClearTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearTableActionPerformed
      DefaultTableModel model = (DefaultTableModel)jTableDisplay.getModel();
      model.setRowCount(0);
    }//GEN-LAST:event_jButtonClearTableActionPerformed

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAddToTableAndWriteToFile;
    private javax.swing.JButton jButtonClearForm;
    private javax.swing.JButton jButtonClearTable;
    private javax.swing.JButton jButtonReadFromFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDisplay;
    private javax.swing.JCheckBox jcheckCoreJava;
    private javax.swing.JCheckBox jcheckHTML;
    private javax.swing.JCheckBox jcheckJS;
    private javax.swing.JComboBox<String> jcmbRound;
    private javax.swing.JLabel jlblID;
    private javax.swing.JLabel jlblID2;
    private javax.swing.JLabel jlblID3;
    private javax.swing.JLabel jlblID4;
    private javax.swing.JLabel jlblID5;
    private javax.swing.JLabel jlblID6;
    private javax.swing.JLabel jlblID7;
    private javax.swing.JLabel jlblName;
    private javax.swing.JRadioButton jradioFemale;
    private javax.swing.JRadioButton jradioMale;
    private javax.swing.JTextField jtxtAge;
    private javax.swing.JTextField jtxtComment;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtID;
    private javax.swing.JTextField jtxtName;
    // End of variables declaration//GEN-END:variables
}
